INSERT INTO Pays (id_pays, nom)
VALUES
('Afghanistan', 'AF'),
('Îles Åland', 'AX'),
('Albanie', 'AL'),
('Algérie', 'DZ'),
('Samoa américaines', 'AS'),
('Andorre', 'AD'),
('Angola', 'AO'),
('Anguilla', 'AI'),
('Antarctique', 'AQ'),
('Antigua-et-Barbuda', 'AG'),
('Argentine', 'AR'),
('Arménie', 'AM'),
('Aruba', 'AW'),
('Australie', 'AU'),
('Autriche', 'AT'),
('Azerbaïdjan', 'AZ'),
('Bahamas', 'BS'),
('Bahreïn', 'BH'),
('Bangladesh', 'BD'),
('Barbade', 'BB'),
('Biélorussie', 'BY'),
('Belgique', 'BE'),
('Belize', 'BZ'),
('Bénin', 'BJ'),
('Bermudes', 'BM'),
('Bhoutan', 'BT'),
('Bolivie', 'BO'),
('Bosnie-Herzégovine', 'BA'),
('Botswana', 'BW'),
('Île Bouvet', 'BV'),
('Brésil', 'BR'),
('British Virgin Islands', 'VG'),
('Territoire britannique de l’Océan Indien', 'IO'),
('Brunei Darussalam', 'BN'),
('Bulgarie', 'BG'),
('Burkina Faso', 'BF'),
('Burundi', 'BI'),
('Cambodge', 'KH'),
('Cameroun', 'CM'),
('Canada', 'CA'),
('Cap-Vert', 'CV'),
('Iles Cayman', 'KY'),
('République centrafricaine', 'CF'),
('Tchad', 'TD'),
('Chili', 'CL'),
('Chine', 'CN'),
('Hong Kong', 'HK'),
('Macao', 'MO'),
('Île Christmas', 'CX'),
('Îles Cocos', 'CC'),
('Colombie', 'CO'),
('Comores', 'KM'),
('République du Congo', 'CG'),
('République démocratique du Congo', 'CD'),
('Îles Cook', 'CK'),
('Costa Rica', 'CR'),
('Côte d’Ivoire', 'CI'),
('Croatie', 'HR'),
('Cuba', 'CU'),
('Chypre', 'CY'),
('République tchèque', 'CZ'),
('Danemark', 'DK'),
('Djibouti', 'DJ'),
('Dominique', 'DM'),
('République dominicaine', 'DO'),
('Équateur', 'EC'),
('Égypte', 'EG'),
('Salvador', 'SV'),
('Guinée équatoriale', 'GQ'),
('Érythrée', 'ER'),
('Estonie', 'EE'),
('Éthiopie', 'ET'),
('Îles Falkland', 'FK'),
('Îles Féroé', 'FO'),
('Fidji', 'FJ'),
('Finlande', 'FI'),
('France', 'FR'),
('Guyane française', 'GF'),
('Polynésie française', 'PF'),
('Terres australes et antarctiques françaises', 'TF'),
('Gabon', 'GA'),
('Gambie', 'GM'),
('Géorgie', 'GE'),
('Allemagne', 'DE'),
('Ghana', 'GH'),
('Gibraltar', 'GI'),
('Grèce', 'GR'),
('Groenland', 'GL'),
('Grenade', 'GD'),
('Guadeloupe', 'GP'),
('Guam', 'GU'),
('Guatemala', 'GT'),
('Guernesey', 'GG'),
('Guinée', 'GN'),
('Guinée-Bissau', 'GW'),
('Guyane', 'GY'),
('Haïti', 'HT'),
('Îles Heard-et-MacDonald', 'HM'),
('Saint-Siège (Vatican)', 'VA'),
('Honduras', 'HN'),
('Hongrie', 'HU'),
('Islande', 'IS'),
('Inde', 'IN'),
('Indonésie', 'ID'),
('Iran', 'IR'),
('Irak', 'IQ'),
('Irlande', 'IE'),
('Ile de Man', 'IM'),
('Israël', 'IL'),
('Italie', 'IT'),
('Jamaïque', 'JM'),
('Japon', 'JP'),
('Jersey', 'JE'),
('Jordanie', 'JO'),
('Kazakhstan', 'KZ'),
('Kenya', 'KE'),
('Kiribati', 'KI'),
('Corée du Nord', 'KP'),
('Corée du Sud', 'KR'),
('Koweït', 'KW'),
('Kirghizistan', 'KG'),
('Laos', 'LA'),
('Lettonie', 'LV'),
('Liban', 'LB'),
('Lesotho', 'LS'),
('Libéria', 'LR'),
('Libye', 'LY'),
('Liechtenstein', 'LI'),
('Lituanie', 'LT'),
('Luxembourg', 'LU'),
('Macédoine', 'MK'),
('Madagascar', 'MG'),
('Malawi', 'MW'),
('Malaisie', 'MY'),
('Maldives', 'MV'),
('Mali', 'ML'),
('Malte', 'MT'),
('Îles Marshall', 'MH'),
('Martinique', 'MQ'),
('Mauritanie', 'MR'),
('Maurice', 'MU'),
('Mayotte', 'YT'),
('Mexique', 'MX'),
('Micronésie', 'FM'),
('Moldavie', 'MD'),
('Monaco', 'MC'),
('Mongolie', 'MN'),
('Monténégro', 'ME'),
('Montserrat', 'MS'),
('Maroc', 'MA'),
('Mozambique', 'MZ'),
('Myanmar', 'MM'),
('Namibie', 'NA'),
('Nauru', 'NR'),
('Népal', 'NP'),
('Pays-Bas', 'NL'),
('Nouvelle-Calédonie', 'NC'),
('Nouvelle-Zélande', 'NZ'),
('Nicaragua', 'NI'),
('Niger', 'NE'),
('Nigeria', 'NG'),
('Niue', 'NU'),
('Île Norfolk', 'NF'),
('Îles Mariannes du Nord', 'MP'),
('Norvège', 'NO'),
('Oman', 'OM'),
('Pakistan', 'PK'),
('Palau', 'PW'),
('Palestine', 'PS'),
('Panama', 'PA'),
('Papouasie-Nouvelle-Guinée', 'PG'),
('Paraguay', 'PY'),
('Pérou', 'PE'),
('Philippines', 'PH'),
('Pitcairn', 'PN'),
('Pologne', 'PL'),
('Portugal', 'PT'),
('Puerto Rico', 'PR'),
('Qatar', 'QA'),
('Réunion', 'RE'),
('Roumanie', 'RO'),
('Russie', 'RU'),
('Rwanda', 'RW'),
('Saint-Barthélemy', 'BL'),
('Sainte-Hélène', 'SH'),
('Saint-Kitts-et-Nevis', 'KN'),
('Sainte-Lucie', 'LC'),
('Saint-Martin (partie française)', 'MF'),
('Saint-Martin (partie néerlandaise)', 'SX'),
('Saint-Pierre-et-Miquelon', 'PM'),
('Saint-Vincent-et-les Grenadines', 'VC'),
('Samoa', 'WS'),
('Saint-Marin', 'SM'),
('Sao Tomé-et-Principe', 'ST'),
('Arabie Saoudite', 'SA'),
('Sénégal', 'SN'),
('Serbie', 'RS'),
('Seychelles', 'SC'),
('Sierra Leone', 'SL'),
('Singapour', 'SG'),
('Slovaquie', 'SK'),
('Slovénie', 'SI'),
('Îles Salomon', 'SB'),
('Somalie', 'SO'),
('Afrique du Sud', 'ZA'),
('Géorgie du Sud et les îles Sandwich du Sud', 'GS'),
('Sud-Soudan', 'SS'),
('Espagne', 'ES'),
('Sri Lanka', 'LK'),
('Soudan', 'SD'),
('Suriname', 'SR'),
('Svalbard et Jan Mayen', 'SJ'),
('Swaziland', 'SZ'),
('Suède', 'SE'),
('Suisse', 'CH'),
('Syrie', 'SY'),
('Taiwan', 'TW'),
('Tadjikistan', 'TJ'),
('Tanzanie', 'TZ'),
('Thaïlande', 'TH'),
('Timor-Leste', 'TL'),
('Togo', 'TG'),
('Tokelau', 'TK'),
('Tonga', 'TO'),
('Trinité-et-Tobago', 'TT'),
('Tunisie', 'TN'),
('Turquie', 'TR'),
('Turkménistan', 'TM'),
('Îles Turques-et-Caïques', 'TC'),
('Tuvalu', 'TV'),
('Ouganda', 'UG'),
('Ukraine', 'UA'),
('Émirats Arabes Unis', 'AE'),
('Royaume-Uni', 'GB'),
('États-Unis', 'US'),
('Îles mineures éloignées des États-Unis', 'UM'),
('Uruguay', 'UY'),
('Ouzbékistan', 'UZ'),
('Vanuatu', 'VU'),
('Venezuela', 'VE'),
('Viêt Nam', 'VN'),
('Îles Vierges américaines', 'VI'),
('Wallis-et-Futuna', 'WF'),
('Sahara occidental', 'EH'),
('Yémen', 'YE'),
('Zimbabwe', 'ZW');

# T shirt homme
INSERT INTO Vetement (marque, description, lien, prix, genre, temperature)
VALUES
('Eden Park', 'T-shirt droit uni col V', 'https://www.galerieslafayette.com/p/t-shirt+droit+uni+col+v-eden+park/33707270/125', 45.00, 'h', 2),
('Calvin Klein', 'T-shirt Tronic', 'https://www.galerieslafayette.com/p/t-shirt+tronic-calvin+klein/48571349/320', 27.50, 'h', 2),
('Replay', 'T-shirt droit en coton uni', 'https://www.galerieslafayette.com/p/t-shirt+droit+en+coton+uni-replay/54482861/140', 35.00, 'h', 2),
('Calvin Klein', 'T-shirt en coton uni slim fit', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+uni+slim+fit-calvin+klein/50689031/320', 22.50, 'h', 2),
('Polo Ralph Lauren', 'T-shirt uni à col V custom slim fit', 'https://www.galerieslafayette.com/p/t-shirt+uni+a+col+v+custom+slim+fit-polo+ralph+lauren/54492014/125', 59.00, 'h', 2),
('Polo Ralph Lauren', 'T-shirt en coton custom slim fit', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+custom+slim+fit-polo+ralph+lauren/55252268/101', 59.00, 'h', 2),
('Polo Ralph Lauren', 'T-shirt chiné', 'https://www.galerieslafayette.com/p/t-shirt+chine-polo+ralph+lauren/55252248/125', 59.00, 'h', 2),
('Calvin Klein', 'T-shirt en coton uni slim fit', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+uni+slim+fit-calvin+klein/50689031/125', 22.50, 'h', 2),
('Eden Park', 'T-shirt droit uni col V', 'https://www.galerieslafayette.com/p/t-shirt+droit+uni+col+v-eden+park/33602813/385', 45.00, 'h', 2),
('Polo Ralph Lauren', 'T-shirt en coton logo', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+logo-polo+ralph+lauren/49889659/103', 41.30, 'h', 2),
('Polo Ralph Lauren', 'T-shirt en coton flammé à col V custom slim fit', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+flamme+a+col+v+custom+slim+fit-polo+ralph+lauren/49889713/119', 41.30, 'h', 2),
('Polo Ralph Lauren', 'T-shirt à rayures contrastantes custom fit', 'https://www.galerieslafayette.com/p/t-shirt+a+rayures+contrastantes+custom+fit-polo+ralph+lauren/49889719/101', 41.30, 'h', 2),
('Calvin Klein', 'T-shirt en coton à message', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+a+message-calvin+klein/50068545/320', 20.00, 'h', 2),
('G-Star', 'T-shirt Zost', 'https://www.galerieslafayette.com/p/t-shirt+zost-g-star/50069280/263', 19.96, 'h', 2),
('Galeries Lafayette', 'T-shirt Mishev', 'https://www.galerieslafayette.com/p/t-shirt+mishev-galeries+lafayette/48362519/320', 7.49, 'h', 2),
('Replay', 'T-shirt droit en coton uni', 'https://www.galerieslafayette.com/p/t-shirt+droit+en+coton+uni-replay/54482868/125', 35.00, 'h', 2),
('The Kooples', 'T-shirt avec collier chaînette amovible à pendentif tête de mort', 'https://www.galerieslafayette.com/p/t-shirt+avec+collier+chainette+amovible+a+pendentif+tete+de+mort-the+kooples/49994548/85', 34.00, 'h', 2),
('Polo Ralph Lauren', 'T-shirt print paysages en all over custom slim fit', 'https://www.galerieslafayette.com/p/t-shirt+print+paysages+en+all+over+custom+slim+fit-polo+ralph+lauren/49889779/2895', 34.50, 'h', 2),
('Ikks', 'T-shirt rayé à col tunisien et manches longues', 'https://www.galerieslafayette.com/p/t-shirt+raye+a+col+tunisien+et+manches+longues-ikks/50030585/99', 34.00, 'h', 2),
('Schott', 'T-shirt Schott', 'https://www.galerieslafayette.com/p/t-shirt+schott-schott/300404392427/92', 30.00, 'h', 2),
('Galeries Lafayette', 'T-shirt Tishron', 'https://www.galerieslafayette.com/p/t-shirt+tishron-galeries+lafayette/52564413/85', 14.99, 'h', 2),
('Harris Wilson', 'T-shirt Kome', 'https://www.galerieslafayette.com/p/t-shirt+kome-harris+wilson/50677497/206', 29.40, 'h', 2),
('Marciano Guess', 'T-SHIRT MARCIANO LOGO', 'https://www.galerieslafayette.com/p/t-shirt+marciano+logo-marciano+guess/300405169361/85', 29.00, 'h', 2),
('Guess', 'T-SHIRT LOGO TRIANGLE', 'https://www.galerieslafayette.com/p/t-shirt+logo+triangle-guess/300404195670/230', 29.90, 'h', 2),
('LeviS', 'T-shirt Housemark Retro ', 'https://www.galerieslafayette.com/p/t-shirt+housemark+retro-levi+s/54335746/125', 29.00, 'h', 2),
('Timberland', 'T-shirt col V', 'https://www.galerieslafayette.com/p/t-shirt+col+v-timberland/50322516/85', 29.00, 'h', 2),
('Armani Exchange', 'T-shirt logotypé print floral loose fit', 'https://www.galerieslafayette.com/p/t-shirt+logotype+print+floral+loose+fit-armani+exchange/50589543/125', 29.50, 'h', 2),
('Harris Wilson', 'T-shirt Kristian', 'https://www.galerieslafayette.com/p/t-shirt+kristian-harris+wilson/50677565/125', 27.00, 'h', 2),
('La Compagnie du Lin', 'T-shirt droit en coton et lin à col V', 'https://www.galerieslafayette.com/p/t-shirt+droit+en+coton+et+lin+a+col+v-la+compagnie+du+lin/53979666/410', 27.30, 'h', 2),
('Calvin Klein', 'T-shirt sérigraphié ', 'https://www.galerieslafayette.com/p/t-shirt+serigraphie-calvin+klein/50068552/498', 27.50, 'h', 2),
('Marc O’Polo', 'T-shirt droit en coton flammé', 'https://www.galerieslafayette.com/p/t-shirt+droit+en+coton+flamme-marc+o+polo/53372816/85', 26.96, 'h', 2),
('Tommy Hilfiger', 'T-shirt en coton uni à flocage contrastant', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+uni+a+flocage+contrastant-tommy+hilfiger/50597051/263', 25.20, 'h', 2),
('Redskins', 'T-shirt Wire Calder', 'https://www.galerieslafayette.com/p/t-shirt+wire+calder-redskins/51216391/125', 24.50, 'h', 2),
('Michael Kors', 'T-shirt en coton marinière', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+mariniere-michael+kors/49543802/88', 24.50, 'h', 2),
('Calvin Klein', 'T-shirt à rectangle contrastant siglé', 'https://www.galerieslafayette.com/p/t-shirt+a+rectangle+contrastant+sigle-calvin+klein/50689057/230', 24.50, 'h', 2),
('Calvin Klein', 'T-shirt à lettrage en velours slim fit', 'https://www.galerieslafayette.com/p/t-shirt+a+lettrage+en+velours+slim+fit-calvin+klein/50689085/85', 24.50, 'h', 2),
('Guess', 'POLO MANCHE LONGUE', 'https://www.galerieslafayette.com/p/polo+manche+longue-guess/300404156025/320', 24.50, 'h', 2),
('Marc O’Polo', 'T-shirt en coton uni shaped fit', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+uni+shaped+fit-marc+o+polo/53372803/204', 23.96, 'h', 2),
('Scotch And Soda', 'T-shirt droit Capsule Felix le Chat', 'https://www.galerieslafayette.com/p/t-shirt+droit+capsule+felix+le+chat-scotch+and+soda/49386524/384', 22.50, 'h', 2),
('Napapijri', 'T-shirt Sancy', 'https://www.galerieslafayette.com/p/t-shirt+sancy-napapijri/49520876/104', 22.00, 'h', 2),
('Calvin Klein', 'T-shirt Boros', 'https://www.galerieslafayette.com/p/t-shirt+boros-calvin+klein/50068657/320', 22.50, 'h', 2),
('Calvin Klein', 'T-shirt en coton uni slim fit', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+uni+slim+fit-calvin+klein/50689031/85', 22.50, 'h', 2),
('Guess', 'T-SHIRT BOUTONS MICRO-MOTIF', 'https://www.galerieslafayette.com/p/t-shirt+boutons+micro-motif-guess/300404453218/101', 22.50, 'h', 2),
('Napapijri', 'T-shirt Sancy', 'https://www.galerieslafayette.com/p/t-shirt+sancy-napapijri/49520876/356', 22.00, 'h', 2),
('LeviS', 'T-shirt en coton logotypé', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+logotype-levi+s/37375644/85', 20.00, 'h', 2),
('Kaporal Jeans', 'T-shirt Loris', 'https://www.galerieslafayette.com/p/t-shirt+loris-kaporal+jeans/49900099/263', 19.50, 'h', 2),
('Guess', 'T-SHIRT COL EN V POCHE DE POITRINE', 'https://www.galerieslafayette.com/p/t-shirt+col+en+v+poche+de+poitrine-guess/300404898171/453', 19.50, 'h', 2),
('Guess', 'T-SHIRT IMPRIME FRONTAL', 'https://www.galerieslafayette.com/p/t-shirt+imprime+frontal-guess/300404898161/320', 19.50, 'h', 2),
('Diesel', 'T-shirt T-Diego', 'https://www.galerieslafayette.com/p/t-shirt+t-diego-diesel/48812211/85', 19.50, 'h', 2),
('Guess', 'T-SHIRT LOGO RELIEF PALMIER', 'https://www.galerieslafayette.com/p/t-shirt+logo+relief+palmier-guess/300405178594/101', 18.00, 'h', 2),
('Chevignon', 'Tee Shirt Ml Straight Col Tunisien', 'https://www.galerieslafayette.com/p/tee+shirt+ml+straight+col+tunisien-chevignon/300404372475/320', 18.00, 'h', 2),
('Petrol Industries', 'T-shirt aspect vintage motif fantaisie', 'https://www.galerieslafayette.com/p/t-shirt+aspect+vintage+motif+fantaisie-petrol+industries/49389796/131', 17.46, 'h', 2),
('Teddy Smith', 'T-shirt Ticlass', 'https://www.galerieslafayette.com/p/t-shirt+ticlass-teddy+smith/49291780/401', 17.50, 'h', 2),
('Teddy Smith', 'T-shirt Ticlass', 'https://www.galerieslafayette.com/p/t-shirt+ticlass-teddy+smith/49291780/99', 17.50, 'h', 2),
('Kaporal Jeans', 'T-shirt Habot', 'https://www.galerieslafayette.com/p/t-shirt+habot-kaporal+jeans/49900035/125', 17.50, 'h', 2),
('Pepe Jeans', 'T-shirt Afremov', 'https://www.galerieslafayette.com/p/t-shirt+afremov-pepe+jeans/48934437/263', 17.50, 'h', 2),
('Sisley', 'T-shirt manches longues en coton flammé', 'https://www.galerieslafayette.com/p/t-shirt+manches+longues+en+coton+flamme-sisley/51314944/125', 17.40, 'h', 2),
('Sisley', 'T-shirt droit en coton flammé', 'https://www.galerieslafayette.com/p/t-shirt+droit+en+coton+flamme-sisley/43319898/85', 17.40, 'h', 2),
('Sisley', 'T-shirt droit en coton flammé à col tunisien', 'https://www.galerieslafayette.com/p/t-shirt+droit+en+coton+flamme+a+col+tunisien-sisley/51314969/320', 17.40, 'h', 2),
('G-Star', 'T-shirt Bellar', 'https://www.galerieslafayette.com/p/t-shirt+bellar-g-star/52614857/125', 17.50, 'h', 2);

# Débardeur homme
INSERT INTO Vetement (marque, description, lien, prix, genre, temperature)
VALUES
('Impetus', 'Débardeur en coton stretch', 'https://www.galerieslafayette.com/p/debardeur+en+coton+stretch-impetus/28038030/320', 21.90, 'h', 3),
('Satisfy', 'Débardeur de running ajouré print homme', 'https://www.galerieslafayette.com/p/debardeur+de+running+ajoure+print+homme-satisfy/49226029/85', 60.00, 'h', 3),
('Scotch And Soda', 'Débardeur droit uni en coton', 'https://www.galerieslafayette.com/p/debardeur+droit+uni+en+coton-scotch+and+soda/49749589/320', 17.50, 'h', 3),
('Guy De Berac', 'Débardeur droit sans manche en laine', 'https://www.galerieslafayette.com/p/debardeur+droit+sans+manche+en+laine-guy+de+berac/33937046/2917', 85.00, 'h', 3),
('Satisfy', 'Débardeur de running en nylon ajouré', 'https://www.galerieslafayette.com/p/debardeur+de+running+en+nylon+ajoure-satisfy/49226035/320', 60.00, 'h', 3),
('Pull-In', 'Débardeur homme GOODBOY', 'https://www.galerieslafayette.com/p/debardeur+homme+goodboy-pull-in/300404666557/230', 17.40, 'h', 3);

ALTER TABLE Vetement ADD item VARCHAR(50);

# pull homme
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('Polo Ralph Lauren', 'Pull en laine mérinos col rond slim fit', 'https://www.galerieslafayette.com/p/pull+en+laine+merinos+col+rond+slim+fit-polo+ralph+lauren/55251915/125', 97.50, 'h', 'pull'),
('Eden Park', 'Pull droit col camionneur zippé', 'https://www.galerieslafayette.com/p/pull+droit+col+camionneur+zippe-eden+park/38797980/320', 77.50, 'h', 'pull'),
('Zadig & Voltaire', 'Pull en coton droit', 'https://www.galerieslafayette.com/p/pull+en+coton+droit-zadig+voltaire/51134602/232', 72.50, 'h', 'pull'),
('The Kooples Sport', 'Sweat en molleton à capuche logotypée et col montant', 'https://www.galerieslafayette.com/p/sweat+en+molleton+a+capuche+logotypee+et+col+montant-the+kooples+sport/49921504/320', 67.50, 'h', 'pull'),
('Carhartt Wip', 'Hoodie kang Chase ', 'https://www.galerieslafayette.com/p/hoodie+kang+chase-carhartt+wip/54814919/230', 62.50, 'h', 'pull'),
('Polo Ralph Lauren', 'Sweat zippé à capuche', 'https://www.galerieslafayette.com/p/sweat+zippe+a+capuche-polo+ralph+lauren/49945112/230', 62.50, 'h', 'pull'),
('Tommy Hilfiger', 'Pull tricolore en coton', 'https://www.galerieslafayette.com/p/pull+tricolore+en+coton-tommy+hilfiger/50594751/206', 59.50, 'h', 'pull'),
('Tommy Hilfiger', 'Pull en coton à fines rayures', 'https://www.galerieslafayette.com/p/pull+en+coton+a+fines+rayures-tommy+hilfiger/50594813/125', 57.50, 'h', 'pull'),
('Tommy Hilfiger', 'Pull droit en maille texturée', 'https://www.galerieslafayette.com/p/pull+droit+en+maille+texturee-tommy+hilfiger/50594819/125', 57.50, 'h', 'pull'),
('Tommy Hilfiger', 'Pull en coton et soie à col V', 'https://www.galerieslafayette.com/p/pull+en+coton+et+soie+a+col+v-tommy+hilfiger/48936786/103', 52.50, 'h', 'pull'),
('Tommy Jeans', 'Sweat en coton flammé logotypé relaxed fit', 'https://www.galerieslafayette.com/p/sweat+en+coton+flamme+logotype+relaxed+fit-tommy+jeans/50632105/85', 52.50, 'h', 'pull'),
('Tommy Hilfiger', 'Pull en coton façon piqué', 'https://www.galerieslafayette.com/p/pull+en+coton+facon+pique-tommy+hilfiger/49106047/101', 52.50, 'h', 'pull'),
('Tommy Jeans', 'Sweat en molleton relaxed fit', 'https://www.galerieslafayette.com/p/sweat+en+molleton+relaxed+fit-tommy+jeans/50632076/125', 52.50, 'h', 'pull'),
('Polo Ralph Lauren', 'Sweat éponge', 'https://www.galerieslafayette.com/p/sweat+eponge-polo+ralph+lauren/49888474/125', 51.00, 'h', 'pull'),
('Calvin Klein', 'Sweat à bande contrastante siglée', 'https://www.galerieslafayette.com/p/sweat+a+bande+contrastante+siglee-calvin+klein/50689005/85', 50.00, 'h', 'pull'),
('Polo Ralph Lauren', 'Sweat éponge', 'https://www.galerieslafayette.com/p/sweat+eponge-polo+ralph+lauren/49888487/401', 49.50, 'h', 'pull'),
('Eden Park', 'Sweat en molleton uni', 'https://www.galerieslafayette.com/p/sweat+en+molleton+uni-eden+park/52186284/125', 41.40, 'h', 'pull'),
('Tommy Hilfiger', 'Sweat en molleton uni', 'https://www.galerieslafayette.com/p/sweat+en+molleton+uni-tommy+hilfiger/50633127/140', 41.40, 'h', 'pull'),
('Diesel', 'Pull K-Pablo', 'https://www.galerieslafayette.com/p/pull+k-pablo-diesel/45608378/125', 29.98, 'h', 'pull'),
('Carhartt Wip', 'Sweat Collège', 'https://www.galerieslafayette.com/p/sweat+college-carhartt+wip/48921942/125', 25.99, 'h', 'pull'),
('LeviS', 'Sweat mollletonné zippé à capuche', 'https://www.galerieslafayette.com/p/sweat+mollletonne+zippe+a+capuche-levi+s/48917584/230', 15.99, 'h', 'pull'),
('Jack & Jones', 'Pull Naval', 'https://www.galerieslafayette.com/p/pull+naval-jack+jones/49891384/125', 19.99, 'h', 'pull'),
('Comptoir GL', 'Pull Loik', 'https://www.galerieslafayette.com/p/pull+loik-comptoir+gl/48766077/125', 32.50, 'h', 'pull'),
('Jack & Jones', 'Sweat Terry Premium by Jack & Jones', 'https://www.galerieslafayette.com/p/sweat+terry+premium+by+jack+jones-jack+jones/49891415/125', 27.99, 'h', 'pull'),
('Galeries Lafayette', 'Sweat Molaye', 'https://www.galerieslafayette.com/p/sweat+molaye-galeries+lafayette/48782094/119', 25.99, 'h', 'pull'),
('Element', 'Sweat en molleton print dessin fantaisie', 'https://www.galerieslafayette.com/p/sweat+en+molleton+print+dessin+fantaisie-element/48958180/62', 84.00, 'h', 'pull'),
('Jack & Jones', 'Sweat Hood Noos', 'https://www.galerieslafayette.com/p/sweat+hood+noos-jack+jones/49890928/120', 19.99, 'h', 'pull'),
('Comptoir GL', 'Pull Loik', 'https://www.galerieslafayette.com/p/pull+loik-comptoir+gl/48766077/60', 25.99, 'h', 'pull'),
('Lacoste', 'Sweat message Roland Garros ', 'https://www.galerieslafayette.com/p/sweat+message+roland+garros-lacoste/49796656/232', 74.50, 'h', 'pull'),
('Jack & Jones', 'Pull Luke Premium by Jack & Jones', 'https://www.galerieslafayette.com/p/pull+luke+premium+by+jack+jones-jack+jones/49890918/104', 30.00, 'h', 'pull'),
('Lacoste', 'Sweat droit en molleton anti UV', 'https://www.galerieslafayette.com/p/sweat+droit+en+molleton+anti+uv-lacoste/46021299/119', 46.62, 'h', 'pull'),
('Comptoir GL', 'Pull Loik', 'https://www.galerieslafayette.com/p/pull+loik-comptoir+gl/48766077/266', 21.99, 'h', 'pull'),
('Calvin Klein', 'Sweat capuche photo Andy Warhol ', 'https://www.galerieslafayette.com/p/sweat+capuche+photo+andy+warhol-calvin+klein/55679692/320', 24.95, 'h', 'pull'),
('Kaporal Jeans', 'Sweat Fusa', 'https://www.galerieslafayette.com/p/sweat+fusa-kaporal+jeans/53897520/232', 17.99, 'h', 'pull'),
('Gant', 'Gilet droit zippé col montant', 'https://www.galerieslafayette.com/p/gilet+droit+zippe+col+montant-gant/51105824/125', 72.00, 'h', 'pull'),
('Element', 'Sweat Cornell', 'https://www.galerieslafayette.com/p/sweat+cornell-element/48958200/125', 97.30, 'h', 'pull'),
('Nike', 'Pull de running léger', 'https://www.galerieslafayette.com/p/pull+de+running+leger-nike/50985907/264', 118.30, 'h', 'pull'),
('Salsa', 'Pull en tricot avec jacquard', 'https://www.galerieslafayette.com/p/pull+en+tricot+avec+jacquard-salsa/300404723926/101', 15.99, 'h', 'pull'),
('Harris Wilson', 'Gilet zippé en coton et laine', 'https://www.galerieslafayette.com/p/gilet+zippe+en+coton+et+laine-harris+wilson/46156305/230', 97.50, 'h', 'pull'),
('Galeries Lafayette', 'Pull Kuble', 'https://www.galerieslafayette.com/p/pull+kuble-galeries+lafayette/48055538/230', 19.99, 'h', 'pull'),
('Eden Park', 'Cardigan droit zippé col montant', 'https://www.galerieslafayette.com/p/cardigan+droit+zippe+col+montant-eden+park/39041308/320', 32.00, 'h', 'pull');

# pantalon homme
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('The Kooples', 'Pantalon de costume Psychedelic Diamond', 'https://www.galerieslafayette.com/p/pantalon+de+costume+psychedelic+diamond-the+kooples/49994228/101', 99.00, 'h', 'pant'),
('The Kooples', 'Pantalon chino coupe carotte', 'https://www.galerieslafayette.com/p/pantalon+chino+coupe+carotte-the+kooples/49920731/320', 79.00, 'h', 'pant'),
('Polo Ralph Lauren', 'Pantalon de jogging', 'https://www.galerieslafayette.com/p/pantalon+de+jogging-polo+ralph+lauren/54914655/125', 109.00, 'h', 'pant'),
('La Compagnie du Lin', 'Pantalon droit en lin', 'https://www.galerieslafayette.com/p/pantalon+droit+en+lin-la+compagnie+du+lin/53979699/85', 80.00, 'h', 'pant'),
('Tommy Hilfiger', 'Pantalon chino Denton straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+denton+straight+fit-tommy+hilfiger/50597778/131', 74.50, 'h', 'pant'),
('Dockers', 'Pantalon chino Alpha slim tapered fit', 'https://www.galerieslafayette.com/p/pantalon+chino+alpha+slim+tapered+fit-dockers/49223544/457', 59.40, 'h', 'pant'),
('Calvin Klein', 'Pantalon chino à ceinture élastiquée', 'https://www.galerieslafayette.com/p/pantalon+chino+a+ceinture+elastiquee-calvin+klein/50068349/125', 54.95, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon chino Kalight slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kalight+slim+fit-galeries+lafayette/49237049/62', 24.99, 'h', 'pant'),
('Scotch And Soda', 'Pantalon chino Mott skinny fit', 'https://www.galerieslafayette.com/p/pantalon+chino+mott+skinny+fit-scotch+and+soda/49749193/264', 49.50, 'h', 'pant'),
('Polo Ralph Lauren', 'Pantalon chino slim', 'https://www.galerieslafayette.com/p/pantalon+chino+slim-polo+ralph+lauren/49910467/101', 49.50, 'h', 'pant'),
('Chevignon', 'Pantalon Cargo Straight', 'https://www.galerieslafayette.com/p/pantalon+cargo+straight-chevignon/300404346503/60', 48.00, 'h', 'pant'),
('Jack & Jones', 'Pantalon chino Cody', 'https://www.galerieslafayette.com/p/pantalon+chino+cody-jack+jones/49891189/131', 34.99, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon Kajolin', 'https://www.galerieslafayette.com/p/pantalon+kajolin-galeries+lafayette/48819829/85', 29.99, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon Kajolin', 'https://www.galerieslafayette.com/p/pantalon+kajolin-galeries+lafayette/48819829/125', 29.99, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon chino Kadroit straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kadroit+straight+fit-galeries+lafayette/47955867/279', 24.99, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon Karelax', 'https://www.galerieslafayette.com/p/pantalon+karelax-galeries+lafayette/47955914/60', 24.99, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon Karelax', 'https://www.galerieslafayette.com/p/pantalon+karelax-galeries+lafayette/47955914/119', 24.99, 'h', 'pant'),
('Dockers', 'Bic Alpha Original Slim Tapered - Stretch Twill', 'https://www.galerieslafayette.com/p/bic+alpha+original+slim+tapered+-+stretch+twill-dockers/33561506/62', 95.00, 'h', 'pant'),
('Dockers', 'Best Pressed Insignia Extra Slim - Stretch Sateen', 'https://www.galerieslafayette.com/p/best+pressed+insignia+extra+slim+-+stretch+sateen-dockers/33561331/125', 105.00, 'h', 'pant'),
('One Step', 'Pantalon chino casual fit', 'https://www.galerieslafayette.com/p/pantalon+chino+casual+fit-one+step/50731465/357', 47.50, 'h', 'pant'),
('Dockers', 'Bic Alpha Original Slim Tapered - Stretch Twill', 'https://www.galerieslafayette.com/p/bic+alpha+original+slim+tapered+-+stretch+twill-dockers/28340550/322', 95.00, 'h', 'pant'),
('Napapijri', 'Pantalon chino Mana Stretch', 'https://www.galerieslafayette.com/p/pantalon+chino+mana+stretch-napapijri/49521183/356', 49.50, 'h', 'pant'),
('Dockers', 'Pantalon chino Alpha Khaki skinny fit', 'https://www.galerieslafayette.com/p/pantalon+chino+alpha+khaki+skinny+fit-dockers/49223553/71', 99.00, 'h', 'pant'),
('Tommy Hilfiger', 'Pantalon chino Denton straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+denton+straight+fit-tommy+hilfiger/45107850/401', 129.00, 'h', 'pant'),
('Faguo', 'Chino Brix coton', 'https://www.galerieslafayette.com/p/chino+brix+coton-faguo/300404456081/457', 48.00, 'h', 'pant'),
('Chevignon', 'Pantalon Chino Straight Coton Lin', 'https://www.galerieslafayette.com/p/pantalon+chino+straight+coton+lin-chevignon/300404677477/384', 63.00, 'h', 'pant'),
('Agnes B.', 'jeans ringo denim', 'https://www.galerieslafayette.com/p/jeans+ringo+denim-agnes+b+/300404078569/101', 160.00, 'h', 'pant'),
('Napapijri', 'Pantalon chino Mana Stretch', 'https://www.galerieslafayette.com/p/pantalon+chino+mana+stretch-napapijri/49521183/104', 49.50, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon chino Radroit straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+radroit+straight+fit-galeries+lafayette/52764392/405', 49.99, 'h', 'pant'),
('G-Star', 'Pantalon Bronson Sport loose fit', 'https://www.galerieslafayette.com/p/pantalon+bronson+sport+loose+fit-g-star/52614749/125', 59.95, 'h', 'pant'),
('Eden Park', 'Pantalon chino en coton regular fit', 'https://www.galerieslafayette.com/p/pantalon+chino+en+coton+regular+fit-eden+park/52310291/72', 72.50, 'h', 'pant'),
('Teddy Smith', 'Pantalon chino slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+slim+fit-teddy+smith/29211970/125', 65.00, 'h', 'pant'),
('Scotch And Soda', 'Pantalon à pinces Blake slim fit', 'https://www.galerieslafayette.com/p/pantalon+a+pinces+blake+slim+fit-scotch+and+soda/49749207/60', 49.50, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon chino Kaslim slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kaslim+slim+fit-galeries+lafayette/47955822/119', 24.99, 'h', 'pant'),
('Chevignon', 'Pantalon Chino Straight Coton Lin', 'https://www.galerieslafayette.com/p/pantalon+chino+straight+coton+lin-chevignon/300404677477/125', 63.00, 'h', 'pant'),
('El Ganso', 'Pantalon chino coton, taille haute', 'https://www.galerieslafayette.com/p/pantalon+chino+coton+taille+haute-el+ganso/47467271/123', 85.00, 'h', 'pant'),
('Dockers', 'Clean Khaki Marina Slim Tapered - Stretch Twill', 'https://www.galerieslafayette.com/p/clean+khaki+marina+slim+tapered+-+stretch+twill-dockers/33561305/60', 95.00, 'h', 'pant'),
('Dockers', 'Best Pressed Insignia Extra Slim - Stretch Sateen', 'https://www.galerieslafayette.com/p/best+pressed+insignia+extra+slim+-+stretch+sateen-dockers/33561351/60', 105.00, 'h', 'pant'),
('Pull-In', 'Pantalon homme DENING RIDE RIDESMOKE', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+ride+ridesmoke-pull-in/300403998528/320', 59.50, 'h', 'pant'),
('Replay', 'Pantalon chino Zeumar slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+zeumar+slim+fit-replay/54482530/119', 149.00, 'h', 'pant'),
('The Kooples', 'Pantalon droit', 'https://www.galerieslafayette.com/p/pantalon+droit-the+kooples/42980768/320', 198.00, 'h', 'pant'),
('Dockers', 'Pantalon chino Alpha slim tapered fit', 'https://www.galerieslafayette.com/p/pantalon+chino+alpha+slim+tapered+fit-dockers/47783502/125', 99.00, 'h', 'pant'),
('Teddy Smith', 'Pantalon chino slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+slim+fit-teddy+smith/29211970/72', 65.00, 'h', 'pant'),
('Pull-In', 'Pantalon homme DENING JUMP PATRIOT', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+jump+patriot-pull-in/300403998592/119', 77.40, 'h', 'pant'),
('G-Star', 'Pantalon chino Bronson slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+bronson+slim+fit-g-star/54410372/62', 99.95, 'h', 'pant'),
('El Ganso', 'Pantalon skinny', 'https://www.galerieslafayette.com/p/pantalon+skinny-el+ganso/47467340/60', 85.00, 'h', 'pant'),
('El Ganso', 'Pantalon à teneur en laine chino uni', 'https://www.galerieslafayette.com/p/pantalon+a+teneur+en+laine+chino+uni-el+ganso/47467275/230', 95.00, 'h', 'pant'),
('Chevignon', 'Pantalon Chino Slim', 'https://www.galerieslafayette.com/p/pantalon+chino+slim-chevignon/300404346509/204', 55.00, 'h', 'pant'),
('Pull-In', 'Pantalon homme DENING RIDE RIDEDARKBLUE', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+ride+ridedarkblue-pull-in/300403998760/119', 64.50, 'h', 'pant'),
('Tommy Jeans', 'Pantalon chino slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+slim+fit-tommy+jeans/50632742/104', 52.50, 'h', 'pant'),
('Replay', 'Pantalon Anbass Corduroy slim fit', 'https://www.galerieslafayette.com/p/pantalon+anbass+corduroy+slim+fit-replay/54482421/279', 145.00, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon chino Kadroit straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kadroit+straight+fit-galeries+lafayette/47955867/266', 24.99, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon chino Kaslim slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kaslim+slim+fit-galeries+lafayette/47955822/233', 24.99, 'h', 'pant'),
('Pull-In', 'Pantalon homme DENING JUMP JUMPRAW', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+jump+jumpraw-pull-in/300404002793/320', 129.00, 'h', 'pant'),
('Pull-In', 'Pantalon homme DENING JUMP SAND', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+jump+sand-pull-in/300403998512/60', 59.40, 'h', 'pant'),
('Dockers', 'Pantalon chino Alpha slim tapered fit', 'https://www.galerieslafayette.com/p/pantalon+chino+alpha+slim+tapered+fit-dockers/47783496/60', 99.00, 'h', 'pant'),
('Chevignon', 'Pantalon Chino Straight', 'https://www.galerieslafayette.com/p/pantalon+chino+straight-chevignon/300404346474/453', 55.00, 'h', 'pant'),
('Pull-In', 'Pantalon homme DENING EPIC WORN', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+epic+worn-pull-in/300404152720/230', 59.40, 'h', 'pant'),
('Galeries Lafayette', 'Pantalon chino Rarelax relaxed fit', 'https://www.galerieslafayette.com/p/pantalon+chino+rarelax+relaxed+fit-galeries+lafayette/52764548/125', 49.99, 'h', 'pant');

# short homme
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('The Kooples', 'Pantalon de costume Psychedelic Diamond', 'https://www.galerieslafayette.com/p/pantalon+de+costume+psychedelic+diamond-the+kooples/49994228/101', 99.00, 'h', 'short'),
('The Kooples', 'Pantalon chino coupe carotte', 'https://www.galerieslafayette.com/p/pantalon+chino+coupe+carotte-the+kooples/49920731/320', 79.00, 'h', 'short'),
('Polo Ralph Lauren', 'Pantalon de jogging', 'https://www.galerieslafayette.com/p/pantalon+de+jogging-polo+ralph+lauren/54914655/125', 109.00, 'h', 'short'),
('La Compagnie du Lin', 'Pantalon droit en lin', 'https://www.galerieslafayette.com/p/pantalon+droit+en+lin-la+compagnie+du+lin/53979699/85', 80.00, 'h', 'short'),
('Tommy Hilfiger', 'Pantalon chino Denton straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+denton+straight+fit-tommy+hilfiger/50597778/131', 74.50, 'h', 'short'),
('Dockers', 'Pantalon chino Alpha slim tapered fit', 'https://www.galerieslafayette.com/p/pantalon+chino+alpha+slim+tapered+fit-dockers/49223544/457', 59.40, 'h', 'short'),
('Calvin Klein', 'Pantalon chino à ceinture élastiquée', 'https://www.galerieslafayette.com/p/pantalon+chino+a+ceinture+elastiquee-calvin+klein/50068349/125', 54.95, 'h', 'short'),
('Galeries Lafayette', 'Pantalon chino Kalight slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kalight+slim+fit-galeries+lafayette/49237049/62', 24.99, 'h', 'short'),
('Scotch And Soda', 'Pantalon chino Mott skinny fit', 'https://www.galerieslafayette.com/p/pantalon+chino+mott+skinny+fit-scotch+and+soda/49749193/264', 49.50, 'h', 'short'),
('Polo Ralph Lauren', 'Pantalon chino slim', 'https://www.galerieslafayette.com/p/pantalon+chino+slim-polo+ralph+lauren/49910467/101', 49.50, 'h', 'short'),
('Chevignon', 'Pantalon Cargo Straight', 'https://www.galerieslafayette.com/p/pantalon+cargo+straight-chevignon/300404346503/60', 48.00, 'h', 'short'),
('Jack & Jones', 'Pantalon chino Cody', 'https://www.galerieslafayette.com/p/pantalon+chino+cody-jack+jones/49891189/131', 34.99, 'h', 'short'),
('Galeries Lafayette', 'Pantalon Kajolin', 'https://www.galerieslafayette.com/p/pantalon+kajolin-galeries+lafayette/48819829/85', 29.99, 'h', 'short'),
('Galeries Lafayette', 'Pantalon Kajolin', 'https://www.galerieslafayette.com/p/pantalon+kajolin-galeries+lafayette/48819829/125', 29.99, 'h', 'short'),
('Galeries Lafayette', 'Pantalon chino Kadroit straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kadroit+straight+fit-galeries+lafayette/47955867/279', 24.99, 'h', 'short'),
('Galeries Lafayette', 'Pantalon Karelax', 'https://www.galerieslafayette.com/p/pantalon+karelax-galeries+lafayette/47955914/60', 24.99, 'h', 'short'),
('Galeries Lafayette', 'Pantalon Karelax', 'https://www.galerieslafayette.com/p/pantalon+karelax-galeries+lafayette/47955914/119', 24.99, 'h', 'short'),
('Dockers', 'Bic Alpha Original Slim Tapered - Stretch Twill', 'https://www.galerieslafayette.com/p/bic+alpha+original+slim+tapered+-+stretch+twill-dockers/33561506/62', 95.00, 'h', 'short'),
('Dockers', 'Best Pressed Insignia Extra Slim - Stretch Sateen', 'https://www.galerieslafayette.com/p/best+pressed+insignia+extra+slim+-+stretch+sateen-dockers/33561331/125', 105.00, 'h', 'short'),
('One Step', 'Pantalon chino casual fit', 'https://www.galerieslafayette.com/p/pantalon+chino+casual+fit-one+step/50731465/357', 47.50, 'h', 'short'),
('Dockers', 'Bic Alpha Original Slim Tapered - Stretch Twill', 'https://www.galerieslafayette.com/p/bic+alpha+original+slim+tapered+-+stretch+twill-dockers/28340550/322', 95.00, 'h', 'short'),
('Napapijri', 'Pantalon chino Mana Stretch', 'https://www.galerieslafayette.com/p/pantalon+chino+mana+stretch-napapijri/49521183/356', 49.50, 'h', 'short'),
('Dockers', 'Pantalon chino Alpha Khaki skinny fit', 'https://www.galerieslafayette.com/p/pantalon+chino+alpha+khaki+skinny+fit-dockers/49223553/71', 99.00, 'h', 'short'),
('Tommy Hilfiger', 'Pantalon chino Denton straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+denton+straight+fit-tommy+hilfiger/45107850/401', 129.00, 'h', 'short'),
('Faguo', 'Chino Brix coton', 'https://www.galerieslafayette.com/p/chino+brix+coton-faguo/300404456081/457', 48.00, 'h', 'short'),
('Chevignon', 'Pantalon Chino Straight Coton Lin', 'https://www.galerieslafayette.com/p/pantalon+chino+straight+coton+lin-chevignon/300404677477/384', 63.00, 'h', 'short'),
('Agnes B.', 'jeans ringo denim', 'https://www.galerieslafayette.com/p/jeans+ringo+denim-agnes+b+/300404078569/101', 160.00, 'h', 'short'),
('Napapijri', 'Pantalon chino Mana Stretch', 'https://www.galerieslafayette.com/p/pantalon+chino+mana+stretch-napapijri/49521183/104', 49.50, 'h', 'short'),
('Galeries Lafayette', 'Pantalon chino Radroit straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+radroit+straight+fit-galeries+lafayette/52764392/405', 49.99, 'h', 'short'),
('G-Star', 'Pantalon Bronson Sport loose fit', 'https://www.galerieslafayette.com/p/pantalon+bronson+sport+loose+fit-g-star/52614749/125', 59.95, 'h', 'short'),
('Eden Park', 'Pantalon chino en coton regular fit', 'https://www.galerieslafayette.com/p/pantalon+chino+en+coton+regular+fit-eden+park/52310291/72', 72.50, 'h', 'short'),
('Teddy Smith', 'Pantalon chino slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+slim+fit-teddy+smith/29211970/125', 65.00, 'h', 'short'),
('Scotch And Soda', 'Pantalon à pinces Blake slim fit', 'https://www.galerieslafayette.com/p/pantalon+a+pinces+blake+slim+fit-scotch+and+soda/49749207/60', 49.50, 'h', 'short'),
('Galeries Lafayette', 'Pantalon chino Kaslim slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kaslim+slim+fit-galeries+lafayette/47955822/119', 24.99, 'h', 'short'),
('Chevignon', 'Pantalon Chino Straight Coton Lin', 'https://www.galerieslafayette.com/p/pantalon+chino+straight+coton+lin-chevignon/300404677477/125', 63.00, 'h', 'short'),
('El Ganso', 'Pantalon chino coton, taille haute', 'https://www.galerieslafayette.com/p/pantalon+chino+coton+taille+haute-el+ganso/47467271/123', 85.00, 'h', 'short'),
('Dockers', 'Clean Khaki Marina Slim Tapered - Stretch Twill', 'https://www.galerieslafayette.com/p/clean+khaki+marina+slim+tapered+-+stretch+twill-dockers/33561305/60', 95.00, 'h', 'short'),
('Dockers', 'Best Pressed Insignia Extra Slim - Stretch Sateen', 'https://www.galerieslafayette.com/p/best+pressed+insignia+extra+slim+-+stretch+sateen-dockers/33561351/60', 105.00, 'h', 'short'),
('Pull-In', 'Pantalon homme DENING RIDE RIDESMOKE', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+ride+ridesmoke-pull-in/300403998528/320', 59.50, 'h', 'short'),
('Replay', 'Pantalon chino Zeumar slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+zeumar+slim+fit-replay/54482530/119', 149.00, 'h', 'short'),
('The Kooples', 'Pantalon droit', 'https://www.galerieslafayette.com/p/pantalon+droit-the+kooples/42980768/320', 198.00, 'h', 'short'),
('Dockers', 'Pantalon chino Alpha slim tapered fit', 'https://www.galerieslafayette.com/p/pantalon+chino+alpha+slim+tapered+fit-dockers/47783502/125', 99.00, 'h', 'short'),
('Teddy Smith', 'Pantalon chino slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+slim+fit-teddy+smith/29211970/72', 65.00, 'h', 'short'),
('Pull-In', 'Pantalon homme DENING JUMP PATRIOT', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+jump+patriot-pull-in/300403998592/119', 77.40, 'h', 'short'),
('G-Star', 'Pantalon chino Bronson slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+bronson+slim+fit-g-star/54410372/62', 99.95, 'h', 'short'),
('El Ganso', 'Pantalon skinny', 'https://www.galerieslafayette.com/p/pantalon+skinny-el+ganso/47467340/60', 85.00, 'h', 'short'),
('El Ganso', 'Pantalon à teneur en laine chino uni', 'https://www.galerieslafayette.com/p/pantalon+a+teneur+en+laine+chino+uni-el+ganso/47467275/230', 95.00, 'h', 'short'),
('Chevignon', 'Pantalon Chino Slim', 'https://www.galerieslafayette.com/p/pantalon+chino+slim-chevignon/300404346509/204', 55.00, 'h', 'short'),
('Pull-In', 'Pantalon homme DENING RIDE RIDEDARKBLUE', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+ride+ridedarkblue-pull-in/300403998760/119', 64.50, 'h', 'short'),
('Tommy Jeans', 'Pantalon chino slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+slim+fit-tommy+jeans/50632742/104', 52.50, 'h', 'short'),
('Replay', 'Pantalon Anbass Corduroy slim fit', 'https://www.galerieslafayette.com/p/pantalon+anbass+corduroy+slim+fit-replay/54482421/279', 145.00, 'h', 'short'),
('Galeries Lafayette', 'Pantalon chino Kadroit straight fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kadroit+straight+fit-galeries+lafayette/47955867/266', 24.99, 'h', 'short'),
('Galeries Lafayette', 'Pantalon chino Kaslim slim fit', 'https://www.galerieslafayette.com/p/pantalon+chino+kaslim+slim+fit-galeries+lafayette/47955822/233', 24.99, 'h', 'short'),
('Pull-In', 'Pantalon homme DENING JUMP JUMPRAW', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+jump+jumpraw-pull-in/300404002793/320', 129.00, 'h', 'short'),
('Pull-In', 'Pantalon homme DENING JUMP SAND', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+jump+sand-pull-in/300403998512/60', 59.40, 'h', 'short'),
('Dockers', 'Pantalon chino Alpha slim tapered fit', 'https://www.galerieslafayette.com/p/pantalon+chino+alpha+slim+tapered+fit-dockers/47783496/60', 99.00, 'h', 'short'),
('Chevignon', 'Pantalon Chino Straight', 'https://www.galerieslafayette.com/p/pantalon+chino+straight-chevignon/300404346474/453', 55.00, 'h', 'short'),
('Pull-In', 'Pantalon homme DENING EPIC WORN', 'https://www.galerieslafayette.com/p/pantalon+homme+dening+epic+worn-pull-in/300404152720/230', 59.40, 'h', 'short'),
('Galeries Lafayette', 'Pantalon chino Rarelax relaxed fit', 'https://www.galerieslafayette.com/p/pantalon+chino+rarelax+relaxed+fit-galeries+lafayette/52764548/125', 49.99, 'h', 'short');

#####

# t-shirt femme
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('Maje', 'T-shirt Tenerif', 'https://www.galerieslafayette.com/p/t-shirt+tenerif-maje/52543194/320', 67.50, 'f', 'ts'),
('Tara Jarmon', 'T-shirt rose bonbon à rayures brodées', 'https://www.galerieslafayette.com/p/t-shirt+rose+bonbon+a+rayures+brodees-tara+jarmon/300404482772/384', 37.50, 'f', 'ts'),
('Zadig & Voltaire', 'T-shirt Meryl', 'https://www.galerieslafayette.com/p/t-shirt+meryl-zadig+voltaire/51135122/85', 98.00, 'f', 'ts'),
('Maje', 'Sweat Tanina', 'https://www.galerieslafayette.com/p/sweat+tanina-maje/52542345/385', 70.00, 'f', 'ts'),
('Zadig & Voltaire', 'T-shirt à inscription', 'https://www.galerieslafayette.com/p/t-shirt+a+inscription-zadig+voltaire/51134585/101', 68.60, 'f', 'ts'),
('Berenice', 'T-shirt Megan', 'https://www.galerieslafayette.com/p/t-shirt+megan-berenice/52510241/85', 65.00, 'f', 'ts'),
('Claudie Pierlot', 'T-shirt manches longues Trocadero', 'https://www.galerieslafayette.com/p/t-shirt+manches+longues+trocadero-claudie+pierlot/49823861/204', 62.50, 'f', 'ts'),
('Berenice', 'T-shirt Mabel', 'https://www.galerieslafayette.com/p/t-shirt+mabel-berenice/52509891/85', 51.00, 'f', 'ts'),
('Claudie Pierlot', 'T-shirt Tears', 'https://www.galerieslafayette.com/p/t-shirt+tears-claudie+pierlot/49825106/204', 51.00, 'f', 'ts'),
('Maje', 'T-shirt Tina', 'https://www.galerieslafayette.com/p/t-shirt+tina-maje/50036451/320', 47.50, 'f', 'ts'),
('Sandro', 'T-shirt avec noeud sur lépaule', 'https://www.galerieslafayette.com/p/t-shirt+avec+noeud+sur+l+epaule-sandro/49828315/85', 47.50, 'f', 'ts'),
('Agnes B.', 'T-shirt Ceylan', 'https://www.galerieslafayette.com/p/t-shirt+ceylan-agnes+b+/52513404/457', 47.50, 'f', 'ts'),
('Maje', 'T-shirt Tonic', 'https://www.galerieslafayette.com/p/t-shirt+tonic-maje/54010570/453', 46.00, 'f', 'ts'),
('Comptoir Des Cotonniers', 'T-shirt Farly', 'https://www.galerieslafayette.com/p/t-shirt+farly-comptoir+des+cotonniers/50836719/85', 44.00, 'f', 'ts'),
('Caroll', 'T-shirt en coton mélange Cecile', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+melange+cecile-caroll/52644330/230', 38.50, 'f', 'ts'),
('Sandro', 'T-shirt droit en coton à motif coeurs', 'https://www.galerieslafayette.com/p/t-shirt+droit+en+coton+a+motif+coeurs-sandro/49831502/320', 32.50, 'f', 'ts'),
('LeviS', 'T-shirt droit à rayures contrastantes', 'https://www.galerieslafayette.com/p/t-shirt+droit+a+rayures+contrastantes-levi+s/54476590/117', 29.00, 'f', 'ts'),
('LeviS', 'T-shirt droit en coton siglé', 'https://www.galerieslafayette.com/p/t-shirt+droit+en+coton+sigle-levi+s/44773229/85', 29.00, 'f', 'ts'),
('Comptoir Des Cotonniers', 'T-shirt en lin', 'https://www.galerieslafayette.com/p/t-shirt+en+lin-comptoir+des+cotonniers/49917640/85', 27.50, 'f', 'ts'),
('LeviS', 'T-shirt classique coton ', 'https://www.galerieslafayette.com/p/t-shirt+classique+coton-levi+s/48938370/85', 21.00, 'f', 'ts'),
('LeviS', 'T-shirt droit uni', 'https://www.galerieslafayette.com/p/t-shirt+droit+uni-levi+s/54477091/85', 20.00, 'f', 'ts'),
('Caroll', 'T-shirt fluide Jenny', 'https://www.galerieslafayette.com/p/t-shirt+fluide+jenny-caroll/52644323/204', 19.50, 'f', 'ts'),
('Balsamik', 'Balsamik - Tunique imprimée, avec plis daisance', 'https://www.galerieslafayette.com/p/balsamik+-+tunique+imprimee+avec+plis+d+aisance-balsamik/300404406033/384', 17.49, 'f', 'ts'),
('Morgan', 'Pull à oeillets et liens à nouer', 'https://www.galerieslafayette.com/p/pull+a+oeillets+et+liens+a+nouer-morgan/300404385562/204', 12.00, 'f', 'ts'),
('Galeries Lafayette', 'T-shirt manches longues Sailor', 'https://www.galerieslafayette.com/p/t-shirt+manches+longues+sailor-galeries+lafayette/48583721/361', 9.99, 'f', 'ts'),
('Galeries Lafayette', 'T-shirt Six', 'https://www.galerieslafayette.com/p/t-shirt+six-galeries+lafayette/48051714/453', 7.99, 'f', 'ts'),
('Esprit', 'T-shirt cintré en coton organique', 'https://www.galerieslafayette.com/p/t-shirt+cintre+en+coton+organique-esprit/49283438/405', 15.99, 'f', 'ts'),
('Caroll', 'T-shirt en coton mélangé Suzie', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+melange+suzie-caroll/52644397/85', 27.00, 'f', 'ts'),
('American Vintage', 'T-shirt à manches longues Jacksonville', 'https://www.galerieslafayette.com/p/t-shirt+a+manches+longues+jacksonville-american+vintage/54134487/85', 45.00, 'f', 'ts'),
('Balsamik', 'Balsamik - Tee-shirt brodé, effet lin', 'https://www.galerieslafayette.com/p/balsamik+-+tee-shirt+brode+effet+lin-balsamik/300402357601/85', 19.99, 'f', 'ts'),
('Caroll', 'T-shirt en coton mélangé Charlie', 'https://www.galerieslafayette.com/p/t-shirt+en+coton+melange+charlie-caroll/52644470/62', 31.50, 'f', 'ts'),
('Topshop', 'T-shirt imprimé lettrage "pas de garcons"', 'https://www.galerieslafayette.com/p/t-shirt+imprime+lettrage+pas+de+garcons+-topshop/52862279/85', 20.00, 'f', 'ts'),
('Queen Mom', 'Top dallaitement', 'https://www.galerieslafayette.com/p/top+d+allaitement-queen+mom/300404690132/85', 34.99, 'f', 'ts'),
('Balsamik', 'Balsamik - Tee-shirts en coton, lot de 2', 'https://www.galerieslafayette.com/p/balsamik+-+tee-shirts+en+coton+lot+de+2-balsamik/300404406169/85', 24.98, 'f', 'ts'),
('Yoga Searcher', 'T-shirt Kirtan', 'https://www.galerieslafayette.com/p/t-shirt+kirtan-yoga+searcher/27560217/385', 49.50, 'f', 'ts'),
('Jodhpur', 'T-shirt Chili', 'https://www.galerieslafayette.com/p/t-shirt+chili-jodhpur/48891892/2918', 17.99, 'f', 'ts'),
('Balsamik', 'Balsamik - Tee-shirt rayé, avec détails guipure', 'https://www.galerieslafayette.com/p/balsamik+-+tee-shirt+raye+avec+details+guipure-balsamik/300402357572/401', 29.99, 'f', 'ts'),
('Galeries Lafayette', 'T-shirt marinière Semao', 'https://www.galerieslafayette.com/p/t-shirt+mariniere+semao-galeries+lafayette/48051868/130', 11.99, 'f', 'ts'),
('Esprit', 'T-shirt cintré en coton organique ', 'https://www.galerieslafayette.com/p/t-shirt+cintre+en+coton+organique-esprit/49283467/85', 15.99, 'f', 'ts'),
('Esprit', 'T-shirt cintré en coton biologique print logo', 'https://www.galerieslafayette.com/p/t-shirt+cintre+en+coton+biologique+print+logo-esprit/49931001/256', 7.99, 'f', 'ts'),
('Queen Mom', 'T-shirt', 'https://www.galerieslafayette.com/p/t-shirt-queen+mom/300404690157/230', 39.99, 'f', 'ts'),
('American Vintage', 'T-shirt à manches longues Jacksonville', 'https://www.galerieslafayette.com/p/t-shirt+a+manches+longues+jacksonville-american+vintage/54134487/60', 31.50, 'f', 'ts'),
('Salsa', 'T-shirt asymétrique avec broderie', 'https://www.galerieslafayette.com/p/t-shirt+asymetrique+avec+broderie-salsa/300403837030/247', 27.73, 'f', 'ts'),
('American Vintage', 'T-shirt à manches longues Jacksonville', 'https://www.galerieslafayette.com/p/t-shirt+a+manches+longues+jacksonville-american+vintage/54134487/233', 45.00, 'f', 'ts'),
('Esprit Maternity', 'T-shirt dallaitement', 'https://www.galerieslafayette.com/p/t-shirt+d+allaitement-esprit+maternity/300402834514/320', 41.99, 'f', 'ts'),
('Sandro', 'T-shirt à col Claudine', 'https://www.galerieslafayette.com/p/t-shirt+a+col+claudine-sandro/49829208/85', 57.50, 'f', 'ts'),
('Morgan', 'T-shirt manches ballons dentelle', 'https://www.galerieslafayette.com/p/t-shirt+manches+ballons+dentelle-morgan/300404385651/320', 35.00, 'f', 'ts'),
('Esprit', 'T-shirt cintré en coton biologique print logo', 'https://www.galerieslafayette.com/p/t-shirt+cintre+en+coton+biologique+print+logo-esprit/49931001/101', 7.99, 'f', 'ts'),
('Queen Mom', 'Top dallaitement', 'https://www.galerieslafayette.com/p/top+d+allaitement-queen+mom/300404690132/318', 34.99, 'f', 'ts'),
('Nike', 'T-shirt à logo', 'https://www.galerieslafayette.com/p/t-shirt+a+logo-nike/51791850/85', 33.00, 'f', 'ts'),
('American Vintage', 'T-shirt à manches longues Jacksonville', 'https://www.galerieslafayette.com/p/t-shirt+a+manches+longues+jacksonville-american+vintage/54134487/101', 31.50, 'f', 'ts'),
('Salsa', 'T-shirt avec détail en tissu dans le dos', 'https://www.galerieslafayette.com/p/t-shirt+avec+detail+en+tissu+dans+le+dos-salsa/300405240680/247', 35.90, 'f', 'ts'),
('La Fiancée du Mekong', 'T-shirt col rond manches 3/4 Sillon', 'https://www.galerieslafayette.com/p/t-shirt+col+rond+manches+3+4+sillon-la+fiancee+du+mekong/300404453613/465', 27.93, 'f', 'ts'),
('LeviS', 'T-shirt Cali', 'https://www.galerieslafayette.com/p/t-shirt+cali-levi+s/48938296/85', 21.00, 'f', 'ts'),
('Lauren', 'T-shirt Hailly', 'https://www.galerieslafayette.com/p/t-shirt+hailly-lauren/51132362/204', 48.00, 'f', 'ts'),
('Pietro Brunelli', 'Las Vegas Tee-shirt de grossesse imprimé -All you need is love-', 'https://www.galerieslafayette.com/p/las+vegas+tee-shirt+de+grossesse+imprime+-all+you+need+is+love--pietro+brunelli/300404790617/85', 16.50, 'f', 'ts'),
('Berenice', 'T-shirt Shiny', 'https://www.galerieslafayette.com/p/t-shirt+shiny-berenice/52511410/263', 59.50, 'f', 'ts'),
('Balsamik', 'Balsamik - Tee-shirt manches courtes volantées', 'https://www.galerieslafayette.com/p/balsamik+-+tee-shirt+manches+courtes+volantees-balsamik/300402357436/467', 29.99, 'f', 'ts'),
('Karl Marc John', 'T-shirt ample Ange', 'https://www.galerieslafayette.com/p/t-shirt+ample+ange-karl+marc+john/52760435/85', 19.00, 'f', 'ts');


# débardeur femme
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('Impetus', 'Débardeur en coton stretch', 'https://www.galerieslafayette.com/p/debardeur+en+coton+stretch-impetus/28038030/320', 21.90, 'f', 'deb'),
('Scotch And Soda', 'Débardeur droit uni en coton', 'https://www.galerieslafayette.com/p/debardeur+droit+uni+en+coton-scotch+and+soda/49749589/320', 17.50, 'f', 'deb'),
('Guy De Berac', 'Débardeur droit sans manche en laine', 'https://www.galerieslafayette.com/p/debardeur+droit+sans+manche+en+laine-guy+de+berac/33937046/2917', 85.00, 'f', 'deb'),
('Satisfy', 'Débardeur de running en nylon ajouré', 'https://www.galerieslafayette.com/p/debardeur+de+running+en+nylon+ajoure-satisfy/49226035/320', 60.00, 'f', 'deb'),
('Satisfy', 'Débardeur de running ajouré print homme', 'https://www.galerieslafayette.com/p/debardeur+de+running+ajoure+print+homme-satisfy/49226029/85', 60.00, 'f', 'deb'),
('Volcom', 'Débardeur Sherwood', 'https://www.galerieslafayette.com/p/debardeur+sherwood-volcom/300404699437/320', 20.00, 'f', 'deb');

# pull femme
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('Polo Ralph Lauren', 'Pull en laine mérinos col rond slim fit', 'https://www.galerieslafayette.com/p/pull+en+laine+merinos+col+rond+slim+fit-polo+ralph+lauren/55251915/125', 145.00, 'f', 'pull'),
('Eden Park', 'Pull droit col camionneur zippé', 'https://www.galerieslafayette.com/p/pull+droit+col+camionneur+zippe-eden+park/38797980/320', 110.00, 'f', 'pull'),
('Zadig & Voltaire', 'Pull en coton droit', 'https://www.galerieslafayette.com/p/pull+en+coton+droit-zadig+voltaire/51134602/232', 97.50, 'f', 'pull'),
('The Kooples Sport', 'Sweat en molleton à capuche logotypée et col montant', 'https://www.galerieslafayette.com/p/sweat+en+molleton+a+capuche+logotypee+et+col+montant-the+kooples+sport/49921504/320', 77.50, 'f', 'pull'),
('Carhartt Wip', 'Hoodie kang Chase ', 'https://www.galerieslafayette.com/p/hoodie+kang+chase-carhartt+wip/54814919/230', 75.00, 'f', 'pull'),
('Polo Ralph Lauren', 'Sweat zippé à capuche', 'https://www.galerieslafayette.com/p/sweat+zippe+a+capuche-polo+ralph+lauren/49945112/230', 72.50, 'f', 'pull'),
('Tommy Hilfiger', 'Pull tricolore en coton', 'https://www.galerieslafayette.com/p/pull+tricolore+en+coton-tommy+hilfiger/50594751/206', 67.50, 'f', 'pull'),
('Tommy Hilfiger', 'Pull en coton à fines rayures', 'https://www.galerieslafayette.com/p/pull+en+coton+a+fines+rayures-tommy+hilfiger/50594813/125', 62.50, 'f', 'pull'),
('Tommy Hilfiger', 'Pull droit en maille texturée', 'https://www.galerieslafayette.com/p/pull+droit+en+maille+texturee-tommy+hilfiger/50594819/125', 62.50, 'f', 'pull'),
('Tommy Hilfiger', 'Pull en coton et soie à col V', 'https://www.galerieslafayette.com/p/pull+en+coton+et+soie+a+col+v-tommy+hilfiger/48936786/103', 59.50, 'f', 'pull'),
('Tommy Jeans', 'Sweat en coton flammé logotypé relaxed fit', 'https://www.galerieslafayette.com/p/sweat+en+coton+flamme+logotype+relaxed+fit-tommy+jeans/50632105/85', 57.50, 'f', 'pull'),
('Tommy Hilfiger', 'Pull en coton façon piqué', 'https://www.galerieslafayette.com/p/pull+en+coton+facon+pique-tommy+hilfiger/49106047/101', 57.50, 'f', 'pull'),
('Tommy Jeans', 'Sweat en molleton relaxed fit', 'https://www.galerieslafayette.com/p/sweat+en+molleton+relaxed+fit-tommy+jeans/50632076/125', 52.50, 'f', 'pull'),
('Polo Ralph Lauren', 'Sweat éponge', 'https://www.galerieslafayette.com/p/sweat+eponge-polo+ralph+lauren/49888474/125', 52.50, 'f', 'pull'),
('Calvin Klein', 'Sweat à bande contrastante siglée', 'https://www.galerieslafayette.com/p/sweat+a+bande+contrastante+siglee-calvin+klein/50689005/85', 52.50, 'f', 'pull'),
('Polo Ralph Lauren', 'Sweat éponge', 'https://www.galerieslafayette.com/p/sweat+eponge-polo+ralph+lauren/49888487/401', 52.50, 'f', 'pull'),
('Eden Park', 'Sweat en molleton uni', 'https://www.galerieslafayette.com/p/sweat+en+molleton+uni-eden+park/52186284/125', 51.00, 'f', 'pull'),
('Tommy Hilfiger', 'Sweat en molleton uni', 'https://www.galerieslafayette.com/p/sweat+en+molleton+uni-tommy+hilfiger/50633127/140', 50.00, 'f', 'pull'),
('Diesel', 'Pull K-Pablo', 'https://www.galerieslafayette.com/p/pull+k-pablo-diesel/45608378/125', 49.50, 'f', 'pull'),
('Carhartt Wip', 'Sweat Collège', 'https://www.galerieslafayette.com/p/sweat+college-carhartt+wip/48921942/125', 41.40, 'f', 'pull'),
('LeviS', 'Sweat mollletonné zippé à capuche', 'https://www.galerieslafayette.com/p/sweat+mollletonne+zippe+a+capuche-levi+s/48917584/230', 41.40, 'f', 'pull'),
('Jack & Jones', 'Pull Naval', 'https://www.galerieslafayette.com/p/pull+naval-jack+jones/49891384/125', 29.98, 'f', 'pull'),
('Comptoir GL', 'Pull Loik', 'https://www.galerieslafayette.com/p/pull+loik-comptoir+gl/48766077/125', 25.99, 'f', 'pull'),
('Jack & Jones', 'Sweat Terry Premium by Jack & Jones', 'https://www.galerieslafayette.com/p/sweat+terry+premium+by+jack+jones-jack+jones/49891415/125', 15.99, 'f', 'pull'),
('Galeries Lafayette', 'Sweat Molaye', 'https://www.galerieslafayette.com/p/sweat+molaye-galeries+lafayette/48782094/119', 19.99, 'f', 'pull'),
('Element', 'Sweat en molleton print dessin fantaisie', 'https://www.galerieslafayette.com/p/sweat+en+molleton+print+dessin+fantaisie-element/48958180/62', 32.50, 'f', 'pull'),
('Jack & Jones', 'Sweat Hood Noos', 'https://www.galerieslafayette.com/p/sweat+hood+noos-jack+jones/49890928/120', 27.99, 'f', 'pull'),
('Comptoir GL', 'Pull Loik', 'https://www.galerieslafayette.com/p/pull+loik-comptoir+gl/48766077/60', 25.99, 'f', 'pull'),
('Lacoste', 'Sweat message Roland Garros ', 'https://www.galerieslafayette.com/p/sweat+message+roland+garros-lacoste/49796656/232', 84.00, 'f', 'pull'),
('Jack & Jones', 'Pull Luke Premium by Jack & Jones', 'https://www.galerieslafayette.com/p/pull+luke+premium+by+jack+jones-jack+jones/49890918/104', 19.99, 'f', 'pull'),
('Lacoste', 'Sweat droit en molleton anti UV', 'https://www.galerieslafayette.com/p/sweat+droit+en+molleton+anti+uv-lacoste/46021299/119', 90.00, 'f', 'pull'),
('Comptoir GL', 'Pull Loik', 'https://www.galerieslafayette.com/p/pull+loik-comptoir+gl/48766077/266', 25.99, 'f', 'pull'),
('Calvin Klein', 'Sweat capuche photo Andy Warhol ', 'https://www.galerieslafayette.com/p/sweat+capuche+photo+andy+warhol-calvin+klein/55679692/320', 119.90, 'f', 'pull'),
('Kaporal Jeans', 'Sweat Fusa', 'https://www.galerieslafayette.com/p/sweat+fusa-kaporal+jeans/53897520/232', 59.00, 'f', 'pull'),
('Gant', 'Gilet droit zippé col montant', 'https://www.galerieslafayette.com/p/gilet+droit+zippe+col+montant-gant/51105824/125', 74.50, 'f', 'pull'),
('Element', 'Sweat Cornell', 'https://www.galerieslafayette.com/p/sweat+cornell-element/48958200/125', 30.00, 'f', 'pull'),
('Nike', 'Pull de running léger', 'https://www.galerieslafayette.com/p/pull+de+running+leger-nike/50985907/264', 100.00, 'f', 'pull'),
('Salsa', 'Pull en tricot avec jacquard', 'https://www.galerieslafayette.com/p/pull+en+tricot+avec+jacquard-salsa/300404723926/101', 46.62, 'f', 'pull'),
('Harris Wilson', 'Gilet zippé en coton et laine', 'https://www.galerieslafayette.com/p/gilet+zippe+en+coton+et+laine-harris+wilson/46156305/230', 95.00, 'f', 'pull'),
('Galeries Lafayette', 'Pull Kuble', 'https://www.galerieslafayette.com/p/pull+kuble-galeries+lafayette/48055538/230', 21.99, 'f', 'pull'),
('G-Star', 'Sweat zippé camouflage ', 'https://www.galerieslafayette.com/p/sweat+zippe+camouflage-g-star/54410194/263', 79.95, 'f', 'pull'),
('Eden Park', 'Cardigan droit zippé col montant', 'https://www.galerieslafayette.com/p/cardigan+droit+zippe+col+montant-eden+park/39041308/320', 115.00, 'f', 'pull'),
('Salsa', 'Pull en maille', 'https://www.galerieslafayette.com/p/pull+en+maille-salsa/300404404440/453', 24.95, 'f', 'pull'),
('Galeries Lafayette', 'Pull cachemire Yashive', 'https://www.galerieslafayette.com/p/pull+cachemire+yashive-galeries+lafayette/52585807/62', 99.99, 'f', 'pull'),
('Galeries Lafayette', 'Pull Maraye', 'https://www.galerieslafayette.com/p/pull+maraye-galeries+lafayette/47905796/125', 17.99, 'f', 'pull'),
('Timberland', 'Gilet coton zippé', 'https://www.galerieslafayette.com/p/gilet+coton+zippe-timberland/50355109/125', 95.00, 'f', 'pull'),
('Polo Ralph Lauren', 'Pull torsadé en laine et cachemire', 'https://www.galerieslafayette.com/p/pull+torsade+en+laine+et+cachemire-polo+ralph+lauren/55252121/320', 185.00, 'f', 'pull'),
('Lacoste', 'Pull droit en jersey de coton', 'https://www.galerieslafayette.com/p/pull+droit+en+jersey+de+coton-lacoste/41573606/104', 72.00, 'f', 'pull'),
('Montagut', 'Gilet homme 100% laine Bernon', 'https://www.galerieslafayette.com/p/gilet+homme+100+laine+bernon-montagut/300401601501/125', 97.30, 'f', 'pull'),
('Montagut', 'Gilet 100% laine col montant zippé Benny', 'https://www.galerieslafayette.com/p/gilet+100+laine+col+montant+zippe+benny-montagut/300401660305/119', 118.30, 'f', 'pull'),
('Galeries Lafayette', 'Pull Merilev', 'https://www.galerieslafayette.com/p/pull+merilev-galeries+lafayette/47969899/410', 15.99, 'f', 'pull'),
('Kitsuné', 'Sweat en molleton à logo tricolore', 'https://www.galerieslafayette.com/p/sweat+en+molleton+a+logo+tricolore-kitsune/50894770/230', 150.00, 'f', 'pull'),
('Nike', 'Sweat à capuche Tech Fleece Windrunner', 'https://www.galerieslafayette.com/p/sweat+a+capuche+tech+fleece+windrunner-nike/50985645/230', 100.00, 'f', 'pull'),
('Sandro', 'Pull droit en laine mérinos', 'https://www.galerieslafayette.com/p/pull+droit+en+laine+merinos-sandro/45968325/101', 97.50, 'f', 'pull'),
('Hilfiger Denim', 'Pull droit en maille fine', 'https://www.galerieslafayette.com/p/pull+droit+en+maille+fine-hilfiger+denim/42893932/104', 95.00, 'f', 'pull'),
('Jack & Jones', 'Pull Luke Premium by Jack & Jones', 'https://www.galerieslafayette.com/p/pull+luke+premium+by+jack+jones-jack+jones/49890918/385', 19.99, 'f', 'pull'),
('Polo Ralph Lauren', 'Pull en laine mérinos col V slim fit', 'https://www.galerieslafayette.com/p/pull+en+laine+merinos+col+v+slim+fit-polo+ralph+lauren/55251988/140', 145.00, 'f', 'pull'),
('Polo Ralph Lauren', 'Sweat molletonné zippé à capuche', 'https://www.galerieslafayette.com/p/sweat+molletonne+zippe+a+capuche-polo+ralph+lauren/54904375/356', 145.00, 'f', 'pull'),
('Chevignon', 'Pull Col Rond En Coton', 'https://www.galerieslafayette.com/p/pull+col+rond+en+coton-chevignon/300404345805/101', 32.00, 'f', 'pull');

# pantalon femme
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('LeviS', 'Jeans Levis 714 straight', 'https://www.galerieslafayette.com/p/jeans+levi+s+714+straight-levi+s/48938175/106', 59.40, 'f', 'pant'),
('LeviS', 'Jeans Levis 711 skinny fit', 'https://www.galerieslafayette.com/p/jeans+levi+s+711+skinny+fit-levi+s/44772745/101', 65.40, 'f', 'pant'),
('Berenice', 'Jeans Berenice Leoni slim', 'https://www.galerieslafayette.com/p/jeans+berenice+leoni+slim-berenice/52509157/101', 79.50, 'f', 'pant'),
('Diesel', 'Jeans Diesel Gracey 084QJ stretch skinny fit', 'https://www.galerieslafayette.com/p/jeans+diesel+gracey+084qj+stretch+skinny+fit-diesel/49372123/106', 75.00, 'f', 'pant'),
('Maje', 'Jeans Maje Paolo boyfriend fit', 'https://www.galerieslafayette.com/p/jeans+maje+paolo+boyfriend+fit-maje/49825710/106', 70.00, 'f', 'pant'),
('Calvin Klein', 'Jeans Calvin Klein Destroy skinny ', 'https://www.galerieslafayette.com/p/jeans+calvin+klein+destroy+skinny-calvin+klein/49868518/106', 69.95, 'f', 'pant'),
('Comptoir Des Cotonniers', 'Jeans Comptoir des Cotonniers slim', 'https://www.galerieslafayette.com/p/jeans+comptoir+des+cotonniers+slim-comptoir+des+cotonniers/49917766/244', 62.50, 'f', 'pant'),
('LeviS', 'Jeans Levis 501 Taper', 'https://www.galerieslafayette.com/p/jeans+levi+s+501+taper-levi+s/44772948/101', 59.40, 'f', 'pant'),
('One Step', 'Jeans One Step Le Lena slim 7/8', 'https://www.galerieslafayette.com/p/jeans+one+step+le+lena+slim+7+8-one+step/49753807/119', 54.00, 'f', 'pant'),
('Ikks', 'Jeans Ikks Slim Sculpt Up', 'https://www.galerieslafayette.com/p/jeans+ikks+slim+sculpt+up-ikks/49679968/101', 54.00, 'f', 'pant'),
('LeviS', 'Jeans Levis 714 straight fit', 'https://www.galerieslafayette.com/p/jeans+levi+s+714+straight+fit-levi+s/48938142/106', 49.50, 'f', 'pant'),
('Tommy Jeans', 'Jeans Tommy Jeans Santana high rise skinny', 'https://www.galerieslafayette.com/p/jeans+tommy+jeans+santana+high+rise+skinny-tommy+jeans/50432022/85', 49.95, 'f', 'pant'),
('Pepe Jeans', 'Jeans Pepe Jeans Mira slim', 'https://www.galerieslafayette.com/p/jeans+pepe+jeans+mira+slim-pepe+jeans/49839404/106', 47.50, 'f', 'pant'),
('Salsa', 'Jeans Colette Skinny avec des paillettes', 'https://www.galerieslafayette.com/p/jeans+colette+skinny+avec+des+paillettes-salsa/300404404336/101', 44.95, 'f', 'pant'),
('Galeries Lafayette', 'Jeans Galeries Lafayette Cslim', 'https://www.galerieslafayette.com/p/jeans+galeries+lafayette+cslim-galeries+lafayette/48043783/102', 19.99, 'f', 'pant'),
('Le Temps Des Cerises', 'Jeans Le Temps Des Cerises slim', 'https://www.galerieslafayette.com/p/jeans+le+temps+des+cerises+slim-le+temps+des+cerises/49796910/85', 34.95, 'f', 'pant'),
('Esprit', 'Jeans Esprit slim', 'https://www.galerieslafayette.com/p/jeans+esprit+slim-esprit/49137168/125', 29.99, 'f', 'pant'),
('Esprit', 'Jeans Esprit slim fit', 'https://www.galerieslafayette.com/p/jeans+esprit+slim+fit-esprit/49137139/106', 24.99, 'f', 'pant'),
('Galeries Lafayette', 'Jeans Galeries Lafayette Pinpin', 'https://www.galerieslafayette.com/p/jeans+galeries+lafayette+pinpin-galeries+lafayette/48051813/60', 23.99, 'f', 'pant'),
('Promod', 'Jean skinny GASPARD Blanc', 'https://www.galerieslafayette.com/p/jean+skinny+gaspard+blanc-promod/300404302617/85', 19.95, 'f', 'pant'),
('Queen Mom', 'Jean flare', 'https://www.galerieslafayette.com/p/jean+flare-queen+mom/300404690536/101', 79.99, 'f', 'pant'),
('Salsa', 'Jeans Wonder Capri avec ?illets', 'https://www.galerieslafayette.com/p/jeans+wonder+capri+avec+illets-salsa/300405241516/101', 99.90, 'f', 'pant'),
('Queen Mom', 'Jean slim', 'https://www.galerieslafayette.com/p/jean+slim-queen+mom/300404690677/106', 79.99, 'f', 'pant'),
('Galeries Lafayette', 'Jeans Galeries Lafayette Pinpin', 'https://www.galerieslafayette.com/p/jeans+galeries+lafayette+pinpin-galeries+lafayette/48051813/85', 23.99, 'f', 'pant'),
('Salsa', 'Jeans Mystery Skinny en denim léger', 'https://www.galerieslafayette.com/p/jeans+mystery+skinny+en+denim+leger-salsa/300405241585/101', 99.90, 'f', 'pant'),
('Salsa', 'Jeans Secret Glamour avec déchirures et filet', 'https://www.galerieslafayette.com/p/jeans+secret+glamour+avec+dechirures+et+filet-salsa/300404725548/101', 49.95, 'f', 'pant'),
('Queen Mom', 'Jean slim', 'https://www.galerieslafayette.com/p/jean+slim-queen+mom/300404690644/230', 89.99, 'f', 'pant'),
('Pepe Jeans', 'Jeans Pepe Jeans Gen Straight', 'https://www.galerieslafayette.com/p/jeans+pepe+jeans+gen+straight-pepe+jeans/49259697/119', 75.00, 'f', 'pant'),
('Diesel', 'Jeans Diesel Livier slim', 'https://www.galerieslafayette.com/p/jeans+diesel+livier+slim-diesel/49372387/104', 130.00, 'f', 'pant'),
('Comptoir Des Cotonniers', 'Jeans Comptoir des Cotonniers Decadente slim fit', 'https://www.galerieslafayette.com/p/jeans+comptoir+des+cotonniers+decadente+slim+fit-comptoir+des+cotonniers/54960363/320', 115.00, 'f', 'pant'),
('Tommy Jeans', 'Jeans Tommy Jeans Santana skinny fit', 'https://www.galerieslafayette.com/p/jeans+tommy+jeans+santana+skinny+fit-tommy+jeans/53693902/322', 99.90, 'f', 'pant'),
('Pepe Jeans', 'Jeans Pepe Jeans Gen straight', 'https://www.galerieslafayette.com/p/jeans+pepe+jeans+gen+straight-pepe+jeans/49259707/101', 99.00, 'f', 'pant'),
('LeviS', 'Jeans Levis 712 slim western', 'https://www.galerieslafayette.com/p/jeans+levi+s+712+slim+western-levi+s/40863751/85', 99.00, 'f', 'pant'),
('Salsa', 'Jeans Colette Capri avec détail de fermeture', 'https://www.galerieslafayette.com/p/jeans+colette+capri+avec+detail+de+fermeture-salsa/300405241551/101', 89.90, 'f', 'pant'),
('Comptoir Des Cotonniers', 'Jeans Comptoir des Cotonniers Decadente slim fit', 'https://www.galerieslafayette.com/p/jeans+comptoir+des+cotonniers+decadente+slim+fit-comptoir+des+cotonniers/54960363/453', 115.00, 'f', 'pant'),
('Salsa', 'Pantalon Shape Up Capri lavage premium', 'https://www.galerieslafayette.com/p/pantalon+shape+up+capri+lavage+premium-salsa/300405241562/101', 99.90, 'f', 'pant'),
('Salsa', 'Colette Capri blanche avec déchirures', 'https://www.galerieslafayette.com/p/colette+capri+blanche+avec+dechirures-salsa/300404724850/85', 44.95, 'f', 'pant'),
('Morgan', 'Jean slim stretch 7/8 effet délavé', 'https://www.galerieslafayette.com/p/jean+slim+stretch+7+8+effet+delave-morgan/300405003645/320', 39.00, 'f', 'pant'),
('Salsa', 'Secret Glamour Push In Capri Premium Wash', 'https://www.galerieslafayette.com/p/secret+glamour+push+in+capri+premium+wash-salsa/300404403258/101', 99.90, 'f', 'pant'),
('Diesel', 'Jeans Diesel Skinzee 0813E skinny fit', 'https://www.galerieslafayette.com/p/jeans+diesel+skinzee+0813e+skinny+fit-diesel/12326227/320', 98.00, 'f', 'pant'),
('Guess', 'JEAN TAILLE HAUTE FEATHER WEIGHT®', 'https://www.galerieslafayette.com/p/jean+taille+haute+feather+weight+-guess/300404691414/101', 59.50, 'f', 'pant'),
('Salsa', 'Pantalons chinos Colette Capri avec micro-print', 'https://www.galerieslafayette.com/p/pantalons+chinos+colette+capri+avec+micro-print-salsa/300404403902/60', 39.95, 'f', 'pant'),
('Esprit Maternity', 'Jean droit', 'https://www.galerieslafayette.com/p/jean+droit-esprit+maternity/300402834841/106', 91.99, 'f', 'pant'),
('Marc O’Polo', 'Jean ALBY KICK flared', 'https://www.galerieslafayette.com/p/jean+alby+kick+flared-marc+o+polo/300404323581/101', 129.00, 'f', 'pant'),
('Queen Mom', 'Jean slim', 'https://www.galerieslafayette.com/p/jean+slim-queen+mom/300404690777/320', 79.99, 'f', 'pant'),
('Salsa', 'Jeans Secret Skinny Soft Touch en denim clair', 'https://www.galerieslafayette.com/p/jeans+secret+skinny+soft+touch+en+denim+clair-salsa/300404724986/101', 49.95, 'f', 'pant'),
('Marc O’Polo', 'Jean ALBY straight', 'https://www.galerieslafayette.com/p/jean+alby+straight-marc+o+polo/300404251264/101', 109.00, 'f', 'pant'),
('Morgan', 'Jean skinny enduit à zips', 'https://www.galerieslafayette.com/p/jean+skinny+enduit+a+zips-morgan/300403804221/320', 45.50, 'f', 'pant'),
('Pepe Jeans', 'Jeans Pepe Jeans Pixie Destroy Skinny', 'https://www.galerieslafayette.com/p/jeans+pepe+jeans+pixie+destroy+skinny-pepe+jeans/53450725/106', 99.00, 'f', 'pant'),
('LeviS', 'Jeans Levis skinny', 'https://www.galerieslafayette.com/p/jeans+levi+s+skinny-levi+s/54476997/101', 99.00, 'f', 'pant'),
('Salsa', 'Jean Bliss en denim clair', 'https://www.galerieslafayette.com/p/jean+bliss+en+denim+clair-salsa/300404724724/101', 89.90, 'f', 'pant'),
('Topshop', 'Jeans Topshop Jamie Moto slim fit', 'https://www.galerieslafayette.com/p/jeans+topshop+jamie+moto+slim+fit-topshop/48117604/320', 55.00, 'f', 'pant'),
('Salsa', 'Jeans Secret Push In Slim enduits', 'https://www.galerieslafayette.com/p/jeans+secret+push+in+slim+enduits-salsa/300404404201/101', 49.95, 'f', 'pant'),
('Pepe Jeans', 'Jeans Pepe Jeans slim Regent', 'https://www.galerieslafayette.com/p/jeans+pepe+jeans+slim+regent-pepe+jeans/49839383/101', 47.50, 'f', 'pant'),
('Salsa', 'Push In Secret Glamour Slim', 'https://www.galerieslafayette.com/p/push+in+secret+glamour+slim-salsa/300404723524/101', 89.90, 'f', 'pant'),
('Desigual', 'Jeans Desigual Louis slim', 'https://www.galerieslafayette.com/p/jeans+desigual+louis+slim-desigual/50330821/101', 49.97, 'f', 'pant'),
('Salsa', 'Jean Push Up Wonder delavage premium', 'https://www.galerieslafayette.com/p/jean+push+up+wonder+delavage+premium-salsa/300403837252/103', 59.50, 'f', 'pant'),
('Noppies', 'Jean droit Beau', 'https://www.galerieslafayette.com/p/jean+droit+beau-noppies/300404488818/101', 79.99, 'f', 'pant'),
('Salsa', 'Jeans Shape Up en denim blanchi', 'https://www.galerieslafayette.com/p/jeans+shape+up+en+denim+blanchi-salsa/300405241317/101', 89.90, 'f', 'pant');

# jupe femme
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('Maje', 'Jupe Jupette', 'https://www.galerieslafayette.com/p/jupe+jupette-maje/50035927/453', 135.00, 'f', 'jupe'),
('The Kooples', 'Jupe longue en soie à volants print cachemire', 'https://www.galerieslafayette.com/p/jupe+longue+en+soie+a+volants+print+cachemire-the+kooples/49922571/101', 131.00, 'f', 'jupe'),
('Devernois', 'Jupe midi ample', 'https://www.galerieslafayette.com/p/jupe+midi+ample-devernois/300405156031/401', 89.00, 'f', 'jupe'),
('Maje', 'Jupe Joshua ', 'https://www.galerieslafayette.com/p/jupe+joshua-maje/52543835/57072', 78.00, 'f', 'jupe'),
('Sandro', 'Jupe courte à volants', 'https://www.galerieslafayette.com/p/jupe+courte+a+volants-sandro/49828245/125', 72.50, 'f', 'jupe'),
('Sandro', 'Jupe avec poches volantées', 'https://www.galerieslafayette.com/p/jupe+avec+poches+volantees-sandro/49828350/401', 62.50, 'f', 'jupe'),
('Sandro', 'Jupe avec poches volantées', 'https://www.galerieslafayette.com/p/jupe+avec+poches+volantees-sandro/49828350/457', 62.50, 'f', 'jupe'),
('Comptoir Des Cotonniers', 'Jupe plissée soleil', 'https://www.galerieslafayette.com/p/jupe+plissee+soleil-comptoir+des+cotonniers/50837217/85', 62.50, 'f', 'jupe'),
('Comptoir Des Cotonniers', 'Jupe plissée à pois', 'https://www.galerieslafayette.com/p/jupe+plissee+a+pois-comptoir+des+cotonniers/50836183/459', 54.00, 'f', 'jupe'),
('Caroll', 'Jupe Olivia', 'https://www.galerieslafayette.com/p/jupe+olivia-caroll/52635432/230', 42.50, 'f', 'jupe'),
('Princesse tam.tam', 'Jupe midi à rayures Bella Vita', 'https://www.galerieslafayette.com/p/jupe+midi+a+rayures+bella+vita-princesse+tam+tam/54394202/384', 42.50, 'f', 'jupe'),
('Galeries Lafayette', 'Jupe Pipa ', 'https://www.galerieslafayette.com/p/jupe+pipa-galeries+lafayette/49073328/125', 19.99, 'f', 'jupe'),
('Caroll', 'Jupe Floriane', 'https://www.galerieslafayette.com/p/jupe+floriane-caroll/52634925/125', 38.00, 'f', 'jupe'),
('Pepe Jeans', 'Jupe Taylor', 'https://www.galerieslafayette.com/p/jupe+taylor-pepe+jeans/49776181/106', 37.50, 'f', 'jupe'),
('Esprit', 'Jupe midi rayée', 'https://www.galerieslafayette.com/p/jupe+midi+rayee-esprit/49930572/384', 35.99, 'f', 'jupe'),
('Karl Marc John', 'Jupe en coton Jive', 'https://www.galerieslafayette.com/p/jupe+en+coton+jive-karl+marc+john/52761833/263', 35.00, 'f', 'jupe'),
('Sinequanone', 'Jupe crayon Smithfield', 'https://www.galerieslafayette.com/p/jupe+crayon+smithfield-sinequanone/300404302172/322', 35.60, 'f', 'jupe'),
('Caroll', 'Jupe Alexander', 'https://www.galerieslafayette.com/p/jupe+alexander-caroll/52635118/453', 28.50, 'f', 'jupe'),
('Caroll', 'Jupe Melinda', 'https://www.galerieslafayette.com/p/jupe+melinda-caroll/52635586/279', 27.00, 'f', 'jupe'),
('Morgan', 'Jupe crayon en sergé', 'https://www.galerieslafayette.com/p/jupe+crayon+en+serge-morgan/300403884100/125', 25.00, 'f', 'jupe'),
('Jodhpur', 'Jupe Cesar', 'https://www.galerieslafayette.com/p/jupe+cesar-jodhpur/47826513/102', 24.99, 'f', 'jupe'),
('La Petite Française', 'Jupe Pâquerette', 'https://www.galerieslafayette.com/p/jupe+paquerette-la+petite+francaise/51907933/125', 23.69, 'f', 'jupe'),
('Galeries Lafayette', 'Jupe Perangere', 'https://www.galerieslafayette.com/p/jupe+perangere-galeries+lafayette/48048802/116', 20.99, 'f', 'jupe'),
('Galeries Lafayette', 'Jupe Paco', 'https://www.galerieslafayette.com/p/jupe+paco-galeries+lafayette/48048751/125', 17.99, 'f', 'jupe'),
('La Fiancée du Mekong', 'Jupe courte Minato', 'https://www.galerieslafayette.com/p/jupe+courte+minato-la+fiancee+du+mekong/300404371015/401', 11.97, 'f', 'jupe'),
('La Fiancée du Mekong', 'Jupe courte Minato', 'https://www.galerieslafayette.com/p/jupe+courte+minato-la+fiancee+du+mekong/300404371039/60', 11.97, 'f', 'jupe'),
('Galeries Lafayette', 'Jupe Paola2', 'https://www.galerieslafayette.com/p/jupe+paola2-galeries+lafayette/49073313/263', 27.98, 'f', 'jupe'),
('Galeries Lafayette', 'Jupe Paola2', 'https://www.galerieslafayette.com/p/jupe+paola2-galeries+lafayette/49073313/101', 27.98, 'f', 'jupe'),
('Salsa', 'Jupe noire Push In', 'https://www.galerieslafayette.com/p/jupe+noire+push+in-salsa/300404724492/320', 53.67, 'f', 'jupe'),
('Esprit', 'Jupe losanges', 'https://www.galerieslafayette.com/p/jupe+losanges-esprit/49931310/117', 41.99, 'f', 'jupe'),
('Guess', 'JUPE EN DENIM', 'https://www.galerieslafayette.com/p/jupe+en+denim-guess/300404015295/101', 79.90, 'f', 'jupe'),
('Balsamik', 'Balsamik - Jupe droite spécial ventre rond', 'https://www.galerieslafayette.com/p/balsamik+-+jupe+droite+special+ventre+rond-balsamik/300404408623/125', 39.99, 'f', 'jupe'),
('La Fiancée du Mekong', 'Jupe évasée fluide en coton Ralia', 'https://www.galerieslafayette.com/p/jupe+evasee+fluide+en+coton+ralia-la+fiancee+du+mekong/300404685379/306', 39.90, 'f', 'jupe'),
('Karl Marc John', 'Jupe portefeuille Joyna', 'https://www.galerieslafayette.com/p/jupe+portefeuille+joyna-karl+marc+john/52761854/125', 39.00, 'f', 'jupe'),
('Max et Moi', 'Jupe en cuir NUTELLA', 'https://www.galerieslafayette.com/p/jupe+en+cuir+nutella-max+et+moi/300405176697/60', 395.00, 'f', 'jupe'),
('Supermom', 'Jupe', 'https://www.galerieslafayette.com/p/jupe-supermom/300403937899/320', 40.99, 'f', 'jupe'),
('Maje', 'Jupe Jarod', 'https://www.galerieslafayette.com/p/jupe+jarod-maje/49826203/320', 78.00, 'f', 'jupe'),
('Sandro', 'Jupe zippée', 'https://www.galerieslafayette.com/p/jupe+zippee-sandro/49826881/320', 82.50, 'f', 'jupe'),
('Liu Jo', 'Jupe courte « Mistero notturno »', 'https://www.galerieslafayette.com/p/jupe+courte+mistero+notturno+-liu+jo/300405194722/401', 155.00, 'f', 'jupe'),
('Balsamik', 'Jupe courte, stature + d1,69m', 'https://www.galerieslafayette.com/p/jupe+courte+stature+d+1+69m-balsamik/300401751335/320', 34.99, 'f', 'jupe'),
('Esprit Maternity', 'Jupe en jean', 'https://www.galerieslafayette.com/p/jupe+en+jean-esprit+maternity/300402838460/106', 68.99, 'f', 'jupe'),
('Noppies', 'Jupe Ilaisa', 'https://www.galerieslafayette.com/p/jupe+ilaisa-noppies/300403937892/48', 68.99, 'f', 'jupe'),
('Guess', 'JUPE PLISSÉE PAILLETTES', 'https://www.galerieslafayette.com/p/jupe+plissee+paillettes-guess/300404898153/256', 119.90, 'f', 'jupe'),
('Maje', 'Jupe Jiba', 'https://www.galerieslafayette.com/p/jupe+jiba-maje/50035742/204', 195.00, 'f', 'jupe'),
('Topshop', 'Jupe évasée zippée', 'https://www.galerieslafayette.com/p/jupe+evasee+zippee-topshop/50850980/230', 34.00, 'f', 'jupe'),
('Devernois', 'Jupe longue imprimée en coton', 'https://www.galerieslafayette.com/p/jupe+longue+imprimee+en+coton-devernois/300404473646/453', 64.00, 'f', 'jupe'),
('Closed', 'Jupe culotte Maja', 'https://www.galerieslafayette.com/p/jupe+culotte+maja-closed/45153035/384', 229.00, 'f', 'jupe'),
('Karl Marc John', 'Jupe portefeuille Joyna', 'https://www.galerieslafayette.com/p/jupe+portefeuille+joyna-karl+marc+john/52761854/178', 39.00, 'f', 'jupe'),
('Max et Moi', 'Jupe POP', 'https://www.galerieslafayette.com/p/jupe+pop-max+et+moi/300405172315/60', 175.00, 'f', 'jupe'),
('Kaporal Jeans', 'Jupe Comic Trip', 'https://www.galerieslafayette.com/p/jupe+comic+trip-kaporal+jeans/45671399/320', 60.00, 'f', 'jupe'),
('Nike', 'Jupe de sport', 'https://www.galerieslafayette.com/p/jupe+de+sport-nike/51791875/85', 36.00, 'f', 'jupe'),
('Msgm', 'Jupe satinée asymétrique ', 'https://www.galerieslafayette.com/p/jupe+satinee+asymetrique-msgm/52423931/256', 127.96, 'f', 'jupe'),
('Liu Jo', 'Jupe mi-longue « Leisure »', 'https://www.galerieslafayette.com/p/jupe+mi-longue+leisure+-liu+jo/300404408278/85', 54.50, 'f', 'jupe'),
('Queen Mom', 'Jupe', 'https://www.galerieslafayette.com/p/jupe-queen+mom/300404691240/318', 39.99, 'f', 'jupe'),
('Pepe Jeans', 'Jupe Rachel', 'https://www.galerieslafayette.com/p/jupe+rachel-pepe+jeans/53450776/320', 85.00, 'f', 'jupe'),
('Tara Jarmon', 'Jupe mi longue bleue nuit', 'https://www.galerieslafayette.com/p/jupe+mi+longue+bleue+nuit-tara+jarmon/48062813/127', 235.00, 'f', 'jupe'),
('Caroll', 'Jupe boutonnée Sophie', 'https://www.galerieslafayette.com/p/jupe+boutonnee+sophie-caroll/52635243/317', 63.00, 'f', 'jupe'),
('Salsa', 'Jupe plissée', 'https://www.galerieslafayette.com/p/jupe+plissee-salsa/300403837177/453', 46.62, 'f', 'jupe'),
('Devernois', 'Jupe droite doublée toile de coton lycra', 'https://www.galerieslafayette.com/p/jupe+droite+doublee+toile+de+coton+lycra-devernois/300404473487/60', 100.80, 'f', 'jupe');

# parapluie
INSERT INTO Vetement (marque, description, lien, prix, genre, item)
VALUES
('Esprit', 'Parapluie', 'https://www.galerieslafayette.com/p/parapluie-esprit/32541781/320', 22.99, 'p', 'para'),
('Pierre Vaux', 'Parapluie pliant automatique à housse zippée', 'https://www.galerieslafayette.com/p/parapluie+pliant+automatique+a+housse+zippee-pierre+vaux/74069956/320', 50.20, 'p', 'para'),
('Isotoner', 'Parapluie Crook X-TRA-SOLIDE', 'https://www.galerieslafayette.com/p/parapluie+crook+x-tra-solide-isotoner/300402953846/60', 36.90, 'p', 'para'),
('Galeries Lafayette', 'Parapluie', 'https://www.galerieslafayette.com/p/parapluie-galeries+lafayette/28945046/320', 22.99, 'p', 'para'),
('Galeries Lafayette', 'Parapluie Keclair', 'https://www.galerieslafayette.com/p/parapluie+keclair-galeries+lafayette/47607604/320', 24.99, 'p', 'para'),
('Galeries Lafayette', 'Parapluie', 'https://www.galerieslafayette.com/p/parapluie-galeries+lafayette/28945491/320', 24.99, 'p', 'para'),
('Guy De Jean', 'Parapluie long', 'https://www.galerieslafayette.com/p/parapluie+long-guy+de+jean/99469694/320', 125.00, 'p', 'para'),
('Galeries Lafayette', 'Parapluie Kropois', 'https://www.galerieslafayette.com/p/parapluie+kropois-galeries+lafayette/47607607/92', 24.99, 'p', 'para'),
('Galeries Lafayette', 'Parapluie', 'https://www.galerieslafayette.com/p/parapluie-galeries+lafayette/28946317/320', 22.99, 'p', 'para'),
('Esprit', 'Parapluie automatique long', 'https://www.galerieslafayette.com/p/parapluie+automatique+long-esprit/57316960/320', 19.99, 'p', 'para'),
('Isotoner', 'PARAPLUIES HOMME Parapluie X-TRA SOLIDE - ouverture/fermeture automatique', 'https://www.galerieslafayette.com/p/parapluies+homme+parapluie+x-tra+solide+-+ouverture+fermeture+automatique-isotoner/300400967844/320', 35.90, 'p', 'para'),
('Isotoner', 'Parapluie Crook homme', 'https://www.galerieslafayette.com/p/parapluie+crook+homme-isotoner/300402953844/320', 33.90, 'p', 'para'),
('Pierre Vaux', 'Parapluie pliant automatique à poignée courbe', 'https://www.galerieslafayette.com/p/parapluie+pliant+automatique+a+poignee+courbe-pierre+vaux/14255517/320', 47.20, 'p', 'para'),
('Isotoner', 'Parapluie X-TRA SOLIDE', 'https://www.galerieslafayette.com/p/parapluie+x-tra+solide-isotoner/300402953836/320', 35.90, 'p', 'para'),
('Esprit', 'Parapluie long manuel', 'https://www.galerieslafayette.com/p/parapluie+long+manuel-esprit/57317208/320', 24.99, 'p', 'para'),
('Isotoner', 'Parapluie Crook X-TRA-SOLIDE', 'https://www.galerieslafayette.com/p/parapluie+crook+x-tra-solide-isotoner/300402953842/320', 36.90, 'p', 'para'),
('Esprit', 'Parapluie', 'https://www.galerieslafayette.com/p/parapluie-esprit/57318057/320', 22.99, 'p', 'para'),
('Isotoner', 'Parapluie Crook homme', 'https://www.galerieslafayette.com/p/parapluie+crook+homme-isotoner/300401463160/320', 33.90, 'p', 'para'),
('Isotoner', 'Parapluie Crook homme', 'https://www.galerieslafayette.com/p/parapluie+crook+homme-isotoner/300402953848/320', 33.90, 'p', 'para'),
('Isotoner', 'Parapluie Cloche transparent - Ouverture manuelle', 'https://www.galerieslafayette.com/p/parapluie+cloche+transparent+-+ouverture+manuelle-isotoner/300401643630/444', 17.94, 'p', 'para'),
('Isotoner', 'Parapluie plat homme', 'https://www.galerieslafayette.com/p/parapluie+plat+homme-isotoner/300401463154/320', 31.90, 'p', 'para'),
('Esprit', 'Parapluie long manuel', 'https://www.galerieslafayette.com/p/parapluie+long+manuel-esprit/57317208/119', 24.99, 'p', 'para'),
('Isotoner', 'Parapluie homme', 'https://www.galerieslafayette.com/p/parapluie+homme-isotoner/300401463156/320', 29.90, 'p', 'para'),
('Galeries Lafayette', 'Parapluie Auto', 'https://www.galerieslafayette.com/p/parapluie+auto-galeries+lafayette/36547658/401', 19.99, 'p', 'para'),
('Isotoner', 'Parapluie X-TRA SOLIDE', 'https://www.galerieslafayette.com/p/parapluie+x-tra+solide-isotoner/300402953850/60', 35.90, 'p', 'para'),
('Isotoner', 'Parapluie Crook X-TRA-SOLIDE', 'https://www.galerieslafayette.com/p/parapluie+crook+x-tra-solide-isotoner/300402953840/320', 36.90, 'p', 'para'),
('Galeries Lafayette', 'Parapluie Auto', 'https://www.galerieslafayette.com/p/parapluie+auto-galeries+lafayette/36547658/71', 19.99, 'p', 'para'),
('Isotoner', 'PARAPLUIES HOMME Parapluie canne GOLF - ouverture manuelle', 'https://www.galerieslafayette.com/p/parapluies+homme+parapluie+canne+golf+-+ouverture+manuelle-isotoner/300400967842/320', 31.90, 'p', 'para'),
('Burberry', 'Parapluie femme télescopique à motif vintage check', 'https://www.galerieslafayette.com/p/parapluie+femme+telescopique+a+motif+vintage+check-burberry/54654477/278', 230.00, 'p', 'para'),
('Jean Paul Gaultier', 'Parapluie automatique rayé', 'https://www.galerieslafayette.com/p/parapluie+automatique+raye-jean+paul+gaultier/38813267/204', 59.00, 'p', 'para'),
('Galeries Lafayette', 'Parapluie Auto', 'https://www.galerieslafayette.com/p/parapluie+auto-galeries+lafayette/36547658/320', 19.99, 'p', 'para'),
('Jean Paul Gaultier', 'Parapluie automatique pliant', 'https://www.galerieslafayette.com/p/parapluie+automatique+pliant-jean+paul+gaultier/64618531/125', 49.90, 'p', 'para'),
('Pierre Vaux', 'Parapluie de golf pliant automatique', 'https://www.galerieslafayette.com/p/parapluie+de+golf+pliant+automatique-pierre+vaux/96505466/320', 35.35, 'p', 'para');

